import { extensionHooksSchema, loadExtensionHooks } from '@jimhoyd/urlcode/extensions';
import type { ExtensionAuthoringContract, ExtensionHookContract, ExtensionInstance, ExtensionRequest, HandlerResult, RuntimeExtension } from '@jimhoyd/urlcode/extensions';
import { alert, escapeHtml, field, markup, postForm } from '@jimhoyd/urlcode-ui';
import { createSignedToken, readSignedToken } from '@jimhoyd/urlcode-ui/host';
import type { UiExtension } from '@jimhoyd/urlcode-ui/host';

const FLOW=/^[a-z][a-z0-9-]{0,63}$/, FIELD=/^[a-z][A-Za-z0-9_]{0,63}$/;
const MAX_BODY=64 * 1024, TOKEN_TTL=10 * 60 * 1000;
type Control='input'|'textarea'|'select'|'checkbox';
type InputType='text'|'email'|'number'|'tel'|'url'|'date'|'datetime-local';

export interface FormOption { value:string; label:string }
export interface FormFieldSpec { label:string; control?:Control; type?:InputType; required?:boolean; minLength?:number; maxLength?:number; minimum?:number; maximum?:number; pattern?:string; enum?:string[]; options?:FormOption[]; description?:string }
export interface FormFlowSpec { mount:string; title:string; submitLabel:string; confirmation:{title:string; message:string}; fields:Record<string,FormFieldSpec> }
interface FormConfig { flows:Record<string,FormFlowSpec>; hooks?:Record<string,unknown> }
export interface FormsExtensionOptions { projectSha256:string; csrfSecret:string|Uint8Array; ui:UiExtension }

const stringSchema={type:'string',minLength:1,maxLength:512};
const fieldSchema={type:'object',additionalProperties:false,required:['label'],properties:{
  label:stringSchema,control:{enum:['input','textarea','select','checkbox']},type:{enum:['text','email','number','tel','url','date','datetime-local']},required:{type:'boolean'},
  minLength:{type:'integer',minimum:0,maximum:65536},maxLength:{type:'integer',minimum:1,maximum:65536},minimum:{type:'number'},maximum:{type:'number'},pattern:{type:'string',minLength:1,maxLength:128},enum:{type:'array',minItems:1,maxItems:128,uniqueItems:true,items:{type:'string',maxLength:512}},description:{type:'string',maxLength:512},
  options:{type:'array',minItems:1,maxItems:128,items:{type:'object',additionalProperties:false,required:['value','label'],properties:{value:{type:'string',maxLength:512},label:{type:'string',maxLength:512}}}},
}};
export const formHookContracts=[{name:'onSubmit',kind:'action',description:'Runs after the extension has admitted and validated a form submission, before the confirmation redirect. It is trusted project code and receives only declared field values.',inputSchema:{type:'object',additionalProperties:false,required:['flow','values'],properties:{flow:{type:'string'},values:{type:'object'}}}}] as const satisfies readonly ExtensionHookContract[];
export const formsConfigSchema={type:'object',additionalProperties:false,required:['flows'],properties:{
  hooks:extensionHooksSchema(formHookContracts),
  flows:{type:'object',minProperties:1,maxProperties:16,propertyNames:{pattern:FLOW.source},additionalProperties:{type:'object',additionalProperties:false,required:['mount','title','submitLabel','confirmation','fields'],properties:{
    mount:{type:'string',pattern:'^/[A-Za-z0-9._~-]+(?:/[A-Za-z0-9._~-]+)*$',maxLength:256},title:stringSchema,submitLabel:stringSchema,
    confirmation:{type:'object',additionalProperties:false,required:['title','message'],properties:{title:stringSchema,message:{type:'string',minLength:1,maxLength:2048}}},
    fields:{type:'object',minProperties:1,maxProperties:32,propertyNames:{pattern:FIELD.source},additionalProperties:fieldSchema},
  }}
}}} as const;
export const formsAuthoring:ExtensionAuthoringContract={
  description:'Declare a bounded server-rendered form flow with fixed fields and confirmation. The forms extension owns HTML escaping, admission, CSRF and field validation; attach auth on the mount when submissions need a signed-in caller.',
  surfaces:[
    {kind:'configuration',name:'flows',description:'Declare each mounted form, its bounded fields, explicit submit label and confirmation page.',path:'urlcode.yaml#extensions.forms.config.flows'},
    {kind:'hook',name:'onSubmit',description:'Optional trusted project action, called only after successful form validation and CSRF admission. It is not sandboxed and must keep external effects idempotent.',path:'urlcode.yaml#extensions.forms.config.hooks.onSubmit'},
    {kind:'extension',name:'mount',description:'Mount each flow as `/contact/*` with GET, HEAD and POST. Add `auth: true` when the form is for signed-in callers.',path:'urlcode.yaml'},
  ],fastChecks:['urlcode validate --project . --host-file <host.mjs> --origin <origin>','urlcode test --project . --host-file <host.mjs> --origin <origin>'],
};

function fail(status:number,message:string,fields?:Record<string,string>):HandlerResult {return {status,headers:[['content-type','text/html; charset=utf-8']],body:fields?`${message}`:message};}
function redirect(path:string):HandlerResult {return {status:303,headers:[['location',path]]};}
function token(secret:string|Uint8Array,flow:string):string {return createSignedToken(secret,{flow},TOKEN_TTL);}
function validToken(secret:string|Uint8Array,flow:string,value:string|undefined):boolean {const parsed=readSignedToken(secret,value,TOKEN_TTL);return parsed?.flow===flow;}
function assertSafePattern(pattern:string):void {if(pattern.length<1||pattern.length>128)throw new Error('pattern must be 1 to 128 characters');try{new RegExp(pattern,'u');}catch{throw new Error('invalid pattern');}let unbounded=0,inClass=false;for(let index=0;index<pattern.length;index++){const char=pattern[index]!;if(char==='\\'){const next=pattern[index+1]??'';if(!inClass&&/[1-9k]/.test(next))throw new Error('pattern backreferences are not supported');index++;continue;}if(inClass){if(char===']')inClass=false;continue;}if(char==='['){inClass=true;continue;}if(char==='('&&/^\(\?<?[=!]/.test(pattern.slice(index,index+4)))throw new Error('pattern lookaround is not supported');if(char===')'&&/^(?:[*+]|\{\d+,\})/.test(pattern.slice(index+1)))throw new Error('pattern cannot repeat a group without a bound');if(char==='*'||char==='+'||(char==='{'&&/^\{\d+,\}/.test(pattern.slice(index))))unbounded++;}if(unbounded>3)throw new Error('pattern allows at most 3 unbounded quantifiers');}
function validateFlow(name:string,flow:FormFlowSpec):void {if(!FLOW.test(name))throw new Error(`Invalid form flow: ${name}`);if(!flow.mount||!flow.mount.startsWith('/'))throw new Error(`Form ${name}: invalid mount`);for(const [fieldName,spec] of Object.entries(flow.fields)){if(!FIELD.test(fieldName))throw new Error(`Form ${name}: invalid field ${fieldName}`);const control=spec.control??'input',numeric=spec.type==='number';if(control==='select'&&(!spec.options?.length))throw new Error(`Form ${name}: select ${fieldName} needs options`);if(control!=='select'&&spec.options)throw new Error(`Form ${name}: options apply only to select ${fieldName}`);if(control!=='input'&&control!=='checkbox'&&spec.type)throw new Error(`Form ${name}: type applies only to input ${fieldName}`);if(control==='checkbox'&&(spec.type||spec.minLength!==undefined||spec.maxLength!==undefined||spec.minimum!==undefined||spec.maximum!==undefined||spec.pattern||spec.enum))throw new Error(`Form ${name}: checkbox ${fieldName} cannot have a type or bounds`);if(numeric&&(spec.minLength!==undefined||spec.maxLength!==undefined||spec.pattern||spec.enum))throw new Error(`Form ${name}: string rules do not apply to numeric ${fieldName}`);if(!numeric&&(spec.minimum!==undefined||spec.maximum!==undefined))throw new Error(`Form ${name}: numeric bounds require type number for ${fieldName}`);if(spec.minLength!==undefined&&spec.maxLength!==undefined&&spec.minLength>spec.maxLength)throw new Error(`Form ${name}: ${fieldName} minLength exceeds maxLength`);if(spec.minimum!==undefined&&spec.maximum!==undefined&&spec.minimum>spec.maximum)throw new Error(`Form ${name}: ${fieldName} minimum exceeds maximum`);if(spec.pattern!==undefined){if((spec.maxLength??0)>128)throw new Error(`Form ${name}: pattern ${fieldName} requires maxLength at most 128`);try{assertSafePattern(spec.pattern);}catch(error){throw new Error(`Form ${name}: pattern ${fieldName} ${(error as Error).message}`,{cause:error});}}}}
function formValues(flow:FormFlowSpec, values:Record<string,string>, errors:Record<string,string>):string {return Object.entries(flow.fields).map(([name,spec])=>{const control=spec.control??'input',uiControl=control==='checkbox'?'input':control;return field({name,label:spec.label,control:uiControl,...(control==='input'?{type:spec.type??'text'}:control==='checkbox'?{type:'checkbox'}:{}),required:spec.required!==false,...(spec.description===undefined?{}:{description:spec.description}),...(errors[name]===undefined?{}:{error:errors[name]}),...(control==='checkbox'?{checked:values[name]==='true'}:{value:values[name]??''}),...(control==='textarea'?{maxLength:spec.maxLength??4096}:{}),...(control==='select'?{options:spec.options!,placeholder:'Choose one'}:{})});}).join('');}
function render(ui:UiExtension, name:string, flow:FormFlowSpec, csrf:string, values:Record<string,string>={}, errors:Record<string,string>={}, status=200):HandlerResult {const body=(Object.keys(errors).length?alert('Correct the highlighted fields.','error'):'')+postForm({action:flow.mount,csrf,fields:formValues(flow,values,errors),label:flow.submitLabel,className:'ui-form-grid'});const page=ui.kit.wrap(markup(body),{title:flow.title});return {status,headers:page.headers,body:page.body};}
function confirmation(ui:UiExtension, flow:FormFlowSpec):HandlerResult {const page=ui.kit.wrap(markup(`<section class="ui-stack"><h1>${escapeHtml(flow.confirmation.title)}</h1><p>${escapeHtml(flow.confirmation.message)}</p></section>`),{title:flow.confirmation.title});return {status:200,headers:page.headers,body:page.body};}
function readForm(request:ExtensionRequest):URLSearchParams|null|undefined {if(request.body.byteLength>MAX_BODY)return undefined;const type=request.headers.get('content-type')?.split(';')[0]?.trim().toLowerCase();if(type!=='application/x-www-form-urlencoded')return null;try{return new URLSearchParams(new TextDecoder('utf-8',{fatal:true}).decode(request.body));}catch{return undefined;}}
function admission(flow:FormFlowSpec, form:URLSearchParams):{values:Record<string,string>;errors:Record<string,string>} {const values:Record<string,string>={},errors:Record<string,string>={};for(const key of new Set(form.keys()))if(key!=='csrf'&&!Object.hasOwn(flow.fields,key))errors[key]='is not a declared field';for(const [name,spec] of Object.entries(flow.fields)){const entries=form.getAll(name);if(entries.length>1){errors[name]='must be supplied once';continue;}const raw=entries[0]??(spec.control==='checkbox'?'false':'');values[name]=raw;const value=spec.control==='checkbox'?(raw==='true'?'true':'false'):raw,required=spec.required!==false;if(spec.control==='checkbox'){if(entries.length&&raw!=='true')errors[name]='must be true or absent';else if(required&&value!=='true')errors[name]='is required';continue;}if(required&&value===''){errors[name]='is required';continue;}if(value===''&&!required)continue;if(spec.minLength!==undefined&&value.length<spec.minLength)errors[name]=`must be at least ${spec.minLength} characters`;else if(spec.maxLength!==undefined&&value.length>spec.maxLength)errors[name]=`must be at most ${spec.maxLength} characters`;else if(spec.pattern!==undefined&&!new RegExp(spec.pattern,'u').test(value))errors[name]='does not match the declared pattern';else if(spec.enum&&!spec.enum.includes(value))errors[name]='is not an allowed value';else if(spec.control==='select'&&!spec.options?.some(option=>option.value===value))errors[name]='is not an allowed option';else if(spec.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))errors[name]='must be a valid email address';else if(spec.type==='number'){const number=Number(value);if(!Number.isFinite(number))errors[name]='must be a number';else if(spec.minimum!==undefined&&number<spec.minimum)errors[name]=`must be at least ${spec.minimum}`;else if(spec.maximum!==undefined&&number>spec.maximum)errors[name]=`must be at most ${spec.maximum}`;}}
return {values,errors};}

/** Creates the forms registration. The CSRF secret is a host-file/operator value and is deliberately absent from project YAML. */
export function createFormsExtension(options:FormsExtensionOptions):RuntimeExtension {if(!/^[a-f0-9]{64}$/.test(options.projectSha256))throw new Error('forms extension requires an explicit operator revision pin');if((typeof options.csrfSecret==='string'&&Buffer.byteLength(options.csrfSecret)<32)||(options.csrfSecret instanceof Uint8Array&&options.csrfSecret.byteLength<32))throw new Error('forms extension requires a CSRF secret of at least 32 bytes');return {name:'forms',version:'1',projectSha256:options.projectSha256,targets:['node','aws','vercel'],schema:formsConfigSchema,hooks:formHookContracts,authoring:formsAuthoring,async activate(raw,context):Promise<ExtensionInstance>{if(!options.ui.active)throw new Error('forms extension requires an active ui extension');const config=raw as unknown as FormConfig;for(const [name,flow] of Object.entries(config.flows)) {validateFlow(name,flow);if(!context.mounts.includes(flow.mount))throw new Error(`Form ${name}: route ${flow.mount}/* with extension: forms is not declared`);}for(const mount of context.mounts)if(!Object.values(config.flows).some(flow=>flow.mount===mount))throw new Error(`Forms mount ${mount} has no declared flow`);const byMount=new Map(Object.entries(config.flows).map(([name,flow])=>[flow.mount,{name,flow}]));const hooks=await loadExtensionHooks<'onSubmit'>(config.hooks,formHookContracts,context);return {async handle(request){const active=request.mount===null?undefined:byMount.get(request.mount);if(!active)return fail(404,'Not found');const {name,flow}=active;const suffix=request.path.slice(flow.mount.length);if(request.method==='GET'||request.method==='HEAD'){const answer=suffix===''?render(options.ui,name,flow,token(options.csrfSecret,name)):suffix==='/confirmation'?confirmation(options.ui,flow):fail(404,'Not found');return request.method==='HEAD'?{...answer,body:undefined}:answer;}if(request.method!=='POST'||suffix!=='')return {status:405,headers:[['allow','GET, HEAD, POST'],['content-type','text/plain; charset=utf-8']],body:'Method not allowed'};const origin=request.headers.get('origin');if(origin!==null&&origin!==context.origin)return fail(403,'Forbidden');const parsed=readForm(request);if(parsed===undefined)return fail(413,'Form body is too large');if(parsed===null)return fail(415,'Form submission requires application/x-www-form-urlencoded');const csrf=parsed.get('csrf')??undefined;if(!validToken(options.csrfSecret,name,csrf))return fail(403,'Forbidden');const {values,errors}=admission(flow,parsed);if(Object.keys(errors).length)return render(options.ui,name,flow,token(options.csrfSecret,name),values,errors,422);try{await hooks.onSubmit?.(Object.freeze({flow:name,values:Object.freeze({...values})}));}catch{return fail(500,'The form could not be submitted');}return redirect(`${flow.mount}/confirmation`);}};}};}
