import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {absolutizeLinks,demoteHeadings,slug,DOCUMENTS,GITHUB_BLOB} from '../scripts/build-llms-full.ts';

const root=resolve(import.meta.dirname,'..');
const script=join(root,'scripts','build-llms-full.ts');

test('llms-full build is deterministic and its contents match the section headings',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'llms-full-'));
  const first=join(dir,'first.txt'),second=join(dir,'second.txt');
  execFileSync(process.execPath,[script,'--out',first],{cwd:dir});
  execFileSync(process.execPath,[script,'--out',second],{cwd:dir});
  const output=await readFile(first,'utf8');
  assert.equal(output,await readFile(second,'utf8'),'output is byte-identical across runs');
  assert.match(output,/^<!-- Generated by scripts\/build-llms-full\.ts/);
  assert.match(output,/about [\d,]+ tokens \(estimate: characters \/ 4\)/);
  const toc=[...output.matchAll(/^\d+\. \[(.+?)\]\(#([a-z0-9-]+)\)/gm)].map(m=>({title:m[1]!,anchor:m[2]!}));
  const headings=[...output.slice(output.indexOf('\n---\n')).matchAll(/^# (.+)$/gm)].map(m=>m[1]!);
  assert.equal(toc.length,DOCUMENTS.length);
  assert.deepEqual(toc.map(e=>e.title),headings);
  for(const entry of toc)assert.equal(entry.anchor,slug(entry.title));
  assert.doesNotMatch(output,/\]\((?:\.\.\/)?(?:docs|schemas|examples)\//,'relative repository links are rewritten');
  assert.ok(output.includes(`${GITHUB_BLOB}docs/AI-AUTHORING.md`));
});

test('llms-full --check rejects a stale copy',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'llms-full-'));
  const out=join(dir,'stale.txt');
  execFileSync(process.execPath,[script,'--out',out]);
  execFileSync(process.execPath,[script,'--check','--out',out]);
  await import('node:fs/promises').then(fs=>fs.appendFile(out,'\nedited'));
  assert.throws(()=>execFileSync(process.execPath,[script,'--check','--out',out],{stdio:'pipe'}),/stale/);
});

test('link rewriting and heading demotion are conservative',()=>{
  assert.equal(absolutizeLinks('[a](YAML-GUIDE.md#x) [b](../schemas/s.json) [c](#top) [d](https://x.y/z) [e](mailto:a@b)','docs/AI-AUTHORING.md'),
    `[a](${GITHUB_BLOB}docs/YAML-GUIDE.md#x) [b](${GITHUB_BLOB}schemas/s.json) [c](#top) [d](https://x.y/z) [e](mailto:a@b)`);
  assert.equal(demoteHeadings('# A\n```md\n# not a heading\n```\n## B'),'## A\n```md\n# not a heading\n```\n### B');
});
