import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {absolutizeLinks,demoteHeadings,pinDocsMentions,slug,DOCUMENTS,githubBlob} from '../scripts/build-llms-full.ts';

const root=resolve(import.meta.dirname,'..');
const script=join(root,'scripts','build-llms-full.ts');
const GITHUB_BLOB=githubBlob((JSON.parse(readFileSync(join(root,'package.json'),'utf8')) as {version:string}).version);

test('llms-full build is deterministic and its contents match the section headings',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'llms-full-'));
  const first=join(dir,'first.txt'),second=join(dir,'second.txt');
  execFileSync(process.execPath,[script,'--out',first],{cwd:dir});
  execFileSync(process.execPath,[script,'--out',second],{cwd:dir});
  const output=await readFile(first,'utf8');
  assert.equal(output,await readFile(second,'utf8'),'output is byte-identical across runs');
  assert.match(output,/^<!-- Generated by scripts\/build-llms-full\.ts/);
  assert.match(output,/<!-- Consolidated URLCode authoring reference\. -->/);
  assert.doesNotMatch(output,/about [\d,]+ tokens/);
  const toc=[...output.matchAll(/^\d+\. \[(.+?)\]\(#([a-z0-9-]+)\)/gm)].map(m=>({title:m[1]!,anchor:m[2]!}));
  const headings=[...output.slice(output.indexOf('\n---\n')).matchAll(/^# (.+)$/gm)].map(m=>m[1]!);
  assert.equal(toc.length,DOCUMENTS.length);
  assert.deepEqual(toc.map(e=>e.title),headings);
  for(const entry of toc)assert.equal(entry.anchor,slug(entry.title));
  assert.doesNotMatch(output,/\]\((?:\.\.\/)?(?:docs|schemas|examples)\//,'relative repository links are rewritten');
  assert.ok(output.includes(`Source: ${GITHUB_BLOB}docs/AI-AUTHORING.md`));
  // An installed copy reads the docs of its own version (#938).
  assert.doesNotMatch(output,/jimhoyd-com\/urlcode\/(?:blob|tree)\/main\//);
});

test('llms-full --check rejects a stale copy',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'llms-full-'));
  const out=join(dir,'stale.txt');
  execFileSync(process.execPath,[script,'--out',out]);
  execFileSync(process.execPath,[script,'--check','--out',out]);
  await import('node:fs/promises').then(fs=>fs.appendFile(out,'\nedited'));
  assert.throws(()=>execFileSync(process.execPath,[script,'--check','--out',out],{stdio:'pipe'}),/stale/);
});

test('link rewriting and heading demotion are conservative',()=>{
  assert.equal(absolutizeLinks('[a](YAML-GUIDE.md#x) [b](../schemas/s.json) [c](#top) [d](https://x.y/z) [e](mailto:a@b)','docs/AI-AUTHORING.md',GITHUB_BLOB),
    `[a](${GITHUB_BLOB}docs/YAML-GUIDE.md#x) [b](${GITHUB_BLOB}schemas/s.json) [c](#top) [d](https://x.y/z) [e](mailto:a@b)`);
  assert.equal(demoteHeadings('# A\n```md\n# not a heading\n```\n## B'),'## A\n```md\n# not a heading\n```\n### B');
});

test('bare docs page mentions of unshipped pages become pinned links (#948)',()=>{
  const shipped=new Set(['docs/TOOLING.md']);
  const source=[
    'See docs/CAPACITY.md, `docs/STORE.md#intervals` and docs/TOOLING.md.',
    '[docs/HTTP.md] [x](docs/ROUTING.md) [y][docs/SITE.md] [`docs/CLOUDFLARE.md`](https://x.y/z) `cat docs/EGRESS.md` `docs/*.md`',
    '```sh',
    'cat docs/MIDDLEWARE.md',
    '```',
  ].join('\n');
  assert.equal(pinDocsMentions(source,GITHUB_BLOB,shipped),[
    `See [docs/CAPACITY.md](${GITHUB_BLOB}docs/CAPACITY.md), [docs/STORE.md#intervals](${GITHUB_BLOB}docs/STORE.md#intervals) and docs/TOOLING.md.`,
    '[docs/HTTP.md] [x](docs/ROUTING.md) [y][docs/SITE.md] [`docs/CLOUDFLARE.md`](https://x.y/z) `cat docs/EGRESS.md` `docs/*.md`',
    '```sh',
    'cat docs/MIDDLEWARE.md',
    '```',
  ].join('\n'));
});
