import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

// `@jimhoyd/urlcode/skills` (packages/core/src/skills.ts) is the supported
// public way for a host to read this package's shipped skill text -- see
// issue #574. It replaces reads of internal package-layout paths such as
// `node_modules/@jimhoyd/urlcode/.claude/skills/...`. Exercise the export
// itself (not a mock), and check it against the real files on disk, the way
// a host importing the published package would.

const root = fileURLToPath(new URL('../', import.meta.url));

test('@jimhoyd/urlcode/skills returns every shipped skill with real text', async () => {
  const { listShippedSkills } = await import('@jimhoyd/urlcode/skills') as
    { listShippedSkills: () => Promise<{ name: string; version: string; text: string }[]> };
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8')) as { version: string };

  const skills = await listShippedSkills();
  assert.deepEqual(skills.map(skill => skill.name).sort(), ['urlcode', 'urlcode-authoring', 'urlcode-operations']);

  const onDisk: Record<string, string> = {
    urlcode: 'skills/urlcode/SKILL.md',
    'urlcode-authoring': '.claude/skills/urlcode-authoring/SKILL.md',
    'urlcode-operations': '.claude/skills/urlcode-operations/SKILL.md',
  };
  for (const skill of skills) {
    assert.equal(skill.version, pkg.version, `${skill.name} version must be the package version`);
    const expected = await readFile(root + onDisk[skill.name], 'utf8');
    assert.equal(skill.text, expected, `${skill.name} text must match the file on disk`);
    assert.match(skill.text, /^---\nname: /, `${skill.name} text should include SKILL.md frontmatter`);
  }
});

// #806: the authoring skill's opt-in hosted-assisted mode and its bounded HTTP
// fallback ship in both distributions, without changing the local-only default.
test('the authoring skill ships its hosted-assisted mode and fallback helper in every distribution', async () => {
  const helper = await readFile(root + '.claude/skills/urlcode-authoring/hosted-plan.mjs', 'utf8');
  assert.equal(await readFile(root + 'packaging/claude-plugin/skills/urlcode-authoring/hosted-plan.mjs', 'utf8'), helper, 'the plugin copy of hosted-plan.mjs is regenerated by npm run docs:agents');
  assert.match(helper, /'https:\/\/api\.urlcode\.ai\/mcp'/);
  const pkg = JSON.parse(await readFile(root + 'package.json', 'utf8')) as { files: string[] };
  assert.ok(pkg.files.includes('.claude/skills'), 'the npm package ships the helper beside SKILL.md');

  for (const path of ['.claude/skills/urlcode-authoring/SKILL.md', 'packaging/claude-plugin/skills/urlcode-authoring/SKILL.md']) {
    const text = await readFile(root + path, 'utf8');
    const description = /^---\nname: urlcode-authoring\ndescription: (.*)\n---\n/.exec(text)?.[1];
    assert.ok(description && description.length <= 1024, `${path}: frontmatter description must stay within 1024 characters`);
    assert.ok(text.split('\n').length <= 500, `${path}: keep SKILL.md under 500 lines; move detail to a supporting file`);
    const at = (heading: string) => { const index = text.indexOf(heading); assert.ok(index >= 0, `${path}: missing ${heading}`); return index; };
    const hosted = at('## Hosted-assisted mode (opt-in)');
    assert.ok(at('## First step: bootstrap before authoring') < hosted, 'bootstrap stays the first step in both modes');
    assert.ok(hosted < at('## Verify before reporting success'));
    const section = text.slice(hosted, at('## No project yet?')).replace(/\s+/g, ' ');
    for (const need of ['Local-only authoring is the default', 'explicitly asks', '`urlcode_task_plan`', 'before writing any YAML', 'runtime.installed.version',
      'https://api.urlcode.ai/mcp', 'A skill cannot register one', 'hosted-plan.mjs', '`hostedGuidance: used`', 'version-mismatch', 'do not upgrade the site',
      'advisory', 'reference-only', 'Never claim hosted guidance you did not receive', 'no secrets'])
      assert.ok(section.includes(need), `${path}: hosted-assisted section must say ${need}`);
  }
});
