export { createAuthService, AuthError } from './auth-core.ts';
export type { AuthService, AuthOptions, AuthUser, AuthSession, AuthSessionResult, AuthCase, AuthDailyMetric, AuthHookStats, AuthSecurityPolicy, AuthRestriction, AuthDevice, AuthPasskey, AuthProof, ExternalAuthProof, PasskeyAuthProof } from './auth-core.ts';
export { apiKeyPrincipalId } from './auth.ts';
export { authPermissions } from './exports.ts';
export type { AuthExports, AuthAccount, AuthActor, AuthCsrf, AuthUrls, AuthPermission } from './exports.ts';
export type { AuthAdministration, AdminAccountRequestInput, AuthDashboard, AuthAccountExport, AuthSessionFilters, AuthPage } from './administration.ts';
export type { BeforeRegisterInput, BeforeRoleChangeInput, AccountCreatedInput, AccountStatusChangedInput, DeletionScheduledInput, AccountDeletedInput, RegistrationMethod } from './lifecycle-hooks.ts';
export { createOidcProvider } from './oidc.ts';
export type { OidcProvider, OidcFlow, OidcIdentity, OidcProviderOptions } from './oidc.ts';
export { createPasskeyProvider } from './passkeys.ts';
export type { PasskeyProvider, StoredPasskey, PasskeyProviderOptions, PasskeySite } from './passkeys.ts';
export * from './registration.ts';
export { createGoogleProvider, createAppleProvider } from './providers.ts';
export type { GoogleProviderOptions, AppleProviderOptions } from './providers.ts';
export { createBackup, restoreBackup } from './backup.ts';
export type { BackupOptions, BackupResult, RestoreOptions } from './backup.ts';
export { createPasswordBreachChecker } from './password-policy.ts';
export type { PasswordBreachOptions } from './password-policy.ts';
export { createAuthPreset } from './presets.ts';
export type { AuthPreset, AuthPresetOptions } from './presets.ts';
export { verifyDeployment } from './deployment-check.ts';
export type { DeploymentCheckOptions, DeploymentCheckResult } from './deployment-check.ts';
export type { ManualRecoveryCase, ManualRecoveryEvidence } from './manual-recovery.ts';
export type { UserQuery } from './user-query.ts';
export type { AdminAccountAction, AdminAccountDelivery, AdminAuthenticationMethods } from './admin-account-operations.ts';
