// Every email auth sends, as the English source it contributes to the mail extension (`contributes.mail`). Operators
// change wording or translate in mail/copy/<locale>.json by '<namespace>.<key>' ('auth.verify-email'). The slot kind is
// the security boundary: a notice declares only `page-link` slots, which mail refuses to carry a query or fragment in,
// so no credential can ride in a notice; only the templates that deliver a credential take a `token-link`.
import type { MailContribution } from '@jimhoyd/urlcode-mail';

export const authMail = {
    namespace: 'auth',
    templates: {
        'admin-verify-email': { subject: 'Account administration requested', text: 'An administrator requested to verify your account email. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-force-password-reset': { subject: 'Account administration requested', text: 'An administrator requested to require a new account password. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-schedule-deletion': { subject: 'Account administration requested', text: 'An administrator requested to schedule account deletion. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-cancel-deletion': { subject: 'Account administration requested', text: 'An administrator requested to cancel account deletion. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-remove-passkey': { subject: 'Account administration requested', text: 'An administrator requested to remove an account passkey. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-remove-external': { subject: 'Account administration requested', text: 'An administrator requested to remove an external sign-in method. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-request-email-change': { subject: 'Account administration requested', text: 'An administrator requested to change your account email. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-assign-roles': { subject: 'Account administration requested', text: 'An administrator requested to change your account role assignments. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'admin-resend-verification': { subject: 'Account administration requested', text: 'An administrator requested to send account email verification. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { link: 'page-link' } },
        'verify-email': { subject: 'Verify your email address', text: 'Verify your email address by opening this link:\n\n{link}\n\nIf you did not request this, ignore this email. Never share this link.', slots: { link: 'token-link' } },
        'reset-password': { subject: 'Reset your password', text: 'Reset your password by opening this link:\n\n{link}\n\nIf you did not request this, ignore this email. Never share this link.', slots: { link: 'token-link' } },
        'cancel-deletion': { subject: 'Cancel account deletion', text: 'Cancel account deletion by opening this link:\n\n{link}\n\nAccount deletion was requested. If you did not request this, use this link to cancel the deletion before the grace period ends. Never share this link.', slots: { link: 'token-link' } },
        invitation: { subject: 'Create your invited account', text: 'Create your invited account by opening this link:\n\n{link}\n\nIf you did not request this, ignore this email. Never share this link.', slots: { link: 'token-link' } },
        'verify-email-change': { subject: 'Verify your new email address', text: 'Verify your new email address by opening this link:\n\n{link}\n\nVerification confirms the new address. The change only activates after the 24-hour cooldown. Never share this link.', slots: { link: 'token-link' } },
        'cancel-email-change': { subject: 'Cancel an email address change', text: 'Cancel an email address change by opening this link:\n\n{link}\n\nA change to your account email was requested. Use this cancellation link before completion if this was not you. Never share this link.', slots: { link: 'token-link' } },
        'sign-in-code': { subject: 'Your sign-in code', text: 'Your sign-in code is: {code}\n\nEnter it at {link}\n\nIf you did not request this, ignore this email. Never share this code.', slots: { link: 'token-link', code: 'code' } },
        'signup-code': { subject: 'Verify your email address', text: 'Your signup code is: {code}\n\nEnter it in the browser where you started signing up at {link}\n\nIf you did not request this, ignore this email. Never share this code.', slots: { link: 'page-link', code: 'code' } },
        'factor-recovery': { subject: 'Second-factor recovery requested', text: 'Someone requested recovery of your account second factor. Confirm in the browser where you started recovery:\n\n{link}\n\nConfirmation starts a 24-hour waiting period. After that period, return to the confirmation link to finish recovery and enroll a new second factor. Existing sessions will be revoked when recovery completes.\n\nIf this was not you, cancel the request before it completes:\n\n{cancelLink}\n\nNever share these links.', slots: { link: 'token-link', cancelLink: 'token-link' } },
        'manual-recovery-warning': { subject: 'Manual account recovery approved', text: 'Two administrators approved a manual recovery request for your account. Completing recovery will replace your sign-in methods and revoke existing sessions. If you did not request this, contact the account operator immediately.', slots: {} },
        'manual-recovery': { subject: 'Restore account access', text: 'Two administrators approved your account recovery. Choose a new password and enroll a second factor at:\n\n{link}\n\nThis link expires in 30 minutes. Your existing sign-in methods and sessions will be revoked when recovery completes. Never share this link.', slots: { link: 'token-link' } },
        'new-device': { subject: 'Account security notification', text: 'A new device signed in to your account.\n\nReview your account at {link}. If this was not you, contact the account operator.', slots: { link: 'page-link' } },
        'password-changed': { subject: 'Account security notification', text: 'Your account password changed.\n\nReview your account at {link}. If this was not you, contact the account operator.', slots: { link: 'page-link' } },
        'email-changed': { subject: 'Account security notification', text: 'Your account email address changed.\n\nReview your account at {link}. If this was not you, contact the account operator.', slots: { link: 'page-link' } },
        'registration-attempt': { subject: 'Account security notification', text: 'Someone tried to create an account with your email address. Your existing account was not changed.\n\nReview your account at {link}. If this was not you, contact the account operator.', slots: { link: 'page-link' } },
        'account-setup': { subject: 'Set up your account', text: 'An administrator created an account for you. Choose a password by opening this link:\n\n{link}\n\nThis link expires in 30 minutes. If you did not expect this, ignore this email. Never share this link.', slots: { link: 'token-link' } },
        'impersonation-started': { subject: 'Account security notification', text: 'An administrator started a ten-minute support session on your account. Security changes are disabled during it.\n\nReason given: {reason}\n\nReview your account at {link}. If you did not expect this, contact the account operator.', slots: { reason: 'text', link: 'page-link' } },
    },
} as const satisfies MailContribution;
export type AuthMailTemplate = keyof typeof authMail.templates;
