import type { ExtensionAuthoringContract } from '@jimhoyd/urlcode/extensions';

/** The store's authoring surfaces, in a module of its own so repository tooling can read them without loading the store or its optional peers. */
export const storeAuthoring: ExtensionAuthoringContract = {
  description: 'Declare collections under extensions.store.config.collections and mount each on a route with `extension: store`. Bounded unique keys, numeric increments, idempotency retention, per-owner records, declared transitions, transfers between balances, membership lists, readers and short-link redirects remain store-owned; no handler code is needed.',
  surfaces: [
    { kind: 'configuration', name: 'collections', description: 'Per-collection mount, a record `schema` (a JSON Schema 2020-12 object schema in the request body profile: flat scalar properties, `additionalProperties: false`; inline, or the name of a project schema under top-level `schemas:` shared with route bodies and MCP tools; a record that breaks it answers `422 invalid_record` with the body-schema issue list), `defaults` (values a create stores for omitted properties) and `readOnlyProperties` (changed only by a transition), bounded unique `key`, numeric `increments`, durable bounded `idempotency`, maxRecords, maxRecordBytes, pageSize, readOnly, `sortable` / `filterable` property lists, and `audit: true` (every write recorded in the audit log with property names and the principal, never values; needs the audit extension, and writes answer `503 audit_backlog` while 1000 events wait to drain). Create, list, read, replace, update and delete need no handler.', path: 'urlcode.yaml',
      goals: ['store', 'persist', 'persisted', 'persistence', 'durable', 'database', 'crud', 'record', 'records', 'collection', 'collections', 'create', 'edit', 'update', 'delete', 'save', 'saved'] },
    { kind: 'configuration', name: 'ownership', description: '`ownership: owner` on a collection: each signed-in principal creates, lists, reads, changes and deletes only its own records: every read and write is scoped to the principal that created the record. Not combined with a unique `key`; `unique: [handle]` keeps a string property unique across every owner (`409 value_taken`, which tells a caller the value is in use, so only for public handles). The mount must be guarded by a principal-providing policy such as `auth: true`. An optional `maxRecordsPerOwner` (at most maxRecords) answers `409 owner_quota_exceeded` at the limit.', path: 'urlcode.yaml',
      goals: ['own', 'owner', 'owners', 'owned', 'ownership', 'their', 'mine', 'per-user', 'personal'] },
    { kind: 'configuration', name: 'transitions', description: 'Declared `transitions` move one record from exact `from` values to constant `set` values (with `stamp: {property: actor|now}`) in one transaction as `POST <mount>/<id>/<name>`; a record not in the `from` state answers `409 transition_conflict`. On an owned collection `by: others` serves the transition on its own `mount` to any principal except the owner (an approval or review step), and `members: <membership collection>` admits only that list\'s members. Not an expression language.', path: 'urlcode.yaml',
      goals: ['approve', 'approves', 'approved', 'approval', 'approvals', 'reject', 'rejects', 'rejected', 'pending', 'submit', 'submits', 'submitted', 'transition', 'transitions', 'cancel', 'cancelled', 'publish', 'published', 'archive', 'archived', 'claim', 'workflow', 'review', 'reviews', 'reviewed'] },
    { kind: 'configuration', name: 'editable', description: '`editable: {status: [draft]}` and `deletable: {status: [draft, rejected]}` on a collection, in the shape of a transition\'s `from` (a value or a list per property, each property in `readOnlyProperties`): outside those states `PUT`/`PATCH` or `DELETE` answer `409 record_locked` and write nothing, on HTTP, `StoreExports` and host transactions alike, so an approved request keeps the values its reviewer saw. Creates are unaffected; the record\'s `Allow` header and a list\'s `allow` name the methods each record takes now.', path: 'urlcode.yaml',
      goals: ['lock', 'locked', 'freeze', 'frozen', 'immutable', 'editable', 'deletable', 'draft', 'drafts', 'approve', 'approved', 'approval', 'submitted', 'finalize', 'finalized'] },
    { kind: 'configuration', name: 'unique', description: '`unique: [handle]` on a collection: no two records, whoever owns them, hold the same value of a listed string property (`maxLength` at most 128, no default, not readOnly); a create or update that would is `409 value_taken`, checked under the write lock through an index. A directory lookup by the handle (`readers` with `properties: [handle]` and `filterable: [handle]`) then names one record, so a transfer recipient cannot be spoofed. The 409 reveals that a value is in use: declare it only for public handles, and constrain case with a `pattern`.', path: 'urlcode.yaml',
      goals: ['unique', 'handle', 'handles', 'username', 'usernames', 'nickname', 'spoof', 'spoofing', 'impersonate', 'duplicate', 'duplicates', 'taken', 'recipient', 'directory'] },
    { kind: 'configuration', name: 'intervals', description: '`intervals: {start, end, within?, scope?, when?}` on a collection: no two records it applies to (those holding the `when` values, such as `{status: booked}`) in one scope with equal `within` values (a room) may hold overlapping half-open `[start, end)` intervals; any create, PUT, PATCH or transition that would answers `409 interval_conflict` and writes nothing. Checked through an index in the write transaction, across owners on an owned collection without naming another owner\'s record. Bounds are both numbers or both `format: date-time` strings in UTC (`Z`). `length` (an ISO 8601 duration such as `PT1H`, or an integer) fixes every slot\'s length and `step` puts both bounds on a grid (`PT1H`: on the hour, UTC) counted from `origin` (default the epoch; a fixed offset such as `1970-01-01T00:00:00+05:30` gives local hours at UTC+05:30, but no daylight saving); a slot that breaks either answers `422 invalid_record`.', path: 'urlcode.yaml',
      goals: ['length', 'duration', 'hour', 'hourly', 'aligned', 'align', 'fixed-length', 'book', 'booking', 'bookings', 'schedule', 'scheduling', 'slot', 'slots', 'appointment', 'appointments', 'reservation', 'reservations', 'reserve', 'calendar', 'overlap', 'overlapping', 'availability', 'shift', 'shifts', 'interval', 'intervals'] },
    { kind: 'configuration', name: 'transfers', description: '`transfers.<name>: {amount, min?, members?}` on a collection: `POST <mount>/transfers/<name>` with `{from, to, amount}` moves a positive whole amount from one record\'s integer `amount` property to another\'s in one transaction, so the sum never changes; a debit below `min` (default 0) answers `409 insufficient_balance` and writes nothing. On an owned collection the caller debits only its own record and may credit anyone\'s. Integers only (a currency in minor units); `If-Match` on `from`, `Idempotency-Key` and audit apply. The amount defaults to 0, is in `readOnlyProperties` and no transition sets it; value comes in through an issuer: a transfer with a negative `min` (the supply outstanding) and `members: <membership collection>`.', path: 'urlcode.yaml',
      goals: ['transfer', 'transfers', 'balance', 'balances', 'credit', 'credits', 'debit', 'wallet', 'wallets', 'points', 'tokens', 'ledger', 'pay', 'payment', 'payments', 'send', 'move', 'conserve', 'budget', 'budgets', 'allowance', 'quota', 'issuer', 'issuers', 'mint'] },
    { kind: 'configuration', name: 'membership', description: 'Permissions as data keyed by the principal id, never roles in auth: a `membership: true` collection with a `key` lists principal ids and has no mount (the operator maintains it with `urlcode-store members` or `addMember`/`removeMember`). A transition\'s or transfer\'s `members`, a collection\'s `create.members` (only members may create; `403` before anything is written) and each `readers.<name>.members` name it.', path: 'urlcode.yaml',
      goals: ['member', 'members', 'members-only', 'invite', 'invited', 'restrict', 'restricted', 'membership', 'reviewer', 'reviewers', 'approver', 'approvers', 'moderator', 'moderators', 'staff', 'team', 'admin', 'admins', 'role', 'roles', 'permission', 'permissions'] },
    { kind: 'configuration', name: 'readers', description: 'An owned collection\'s `readers: {<name>: {mount, members?, showOwner?, properties?}}` declares named read-only mounts on which the members of a membership collection list (with the collection\'s limit, cursor, sort and filters) and read every owner\'s records; owners keep their own view on the collection mount. `properties` makes a mount a projection (`id` and the listed properties only, sorted and filtered by those only) and `members` optional: a directory any signed-in principal searches, for example to find a transfer recipient\'s wallet id by name without seeing any balance. One collection may have both, e.g. `readers: {directory: {mount: /api/directory, properties: [name]}, audit: {mount: /api/audit, members: treasurers, showOwner: true}}`.', path: 'urlcode.yaml',
      goals: ['directory', 'lookup', 'find', 'search', 'recipient', 'recipients', 'projection', 'public', 'reviewer', 'reviewers', 'review', 'moderator', 'moderators', 'approver', 'approvers', 'staff', 'admin', 'admins', 'everyone', 'all'] },
    { kind: 'configuration', name: 'shortLinks', description: 'Optional public GET redirect mounts that look up a collection key, use a declared `format: uri` destination property that takes only HTTP(S) URLs, and atomically increment a declared counter.', path: 'urlcode.yaml',
      goals: ['shortener', 'short', 'shortlink', 'shortlinks', 'slug', 'slugs', 'clicks'] },
    { kind: 'extension', name: 'mount', description: 'Collection routes `/api/<name>/*` use GET, HEAD, POST, PUT, PATCH, DELETE; short-link routes use GET, HEAD. Readers routes use GET, HEAD and a `by: others` transition route uses POST. Add `auth: true` to any private mount; an `ownership: owner` collection requires it (or another principal-providing policy).', path: 'urlcode.yaml' },
  ],
  fastChecks: ['urlcode validate --local --project app --host-file host.mjs --local-review', 'urlcode test --project app --host-file host.mjs --local-review'],
};
