import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { TOTP } from 'otpauth';
import type { AuthServiceInternal as AuthService } from '../src/auth-core.ts';
import { sessionReference } from '../src/auth-core.ts';
import { createAuthService, password, setup, verifyOwnMailbox } from './support/auth-core.ts';

async function factorProof(service: AuthService, credentialId: string, browserHash = '2'.repeat(64)) {
    const stored = (await service.getPasskey(credentialId))!;
    const token = await service.createSecondFactorProof({ browserHash, proof: { ...stored.proof, newCounter: stored.credential.counter + 1 } });
    return { token, browserHash };
}
test('TOTP secrets are encrypted, codes cannot replay and recovery codes are single-use', async (t) => {
    const { service, database, advance, now } = await setup(t), user = await service.register({ email: 'mfa@example.com', password });
    await verifyOwnMailbox(service, user.user.email, user.token);
    const setupTotp = await service.beginTotp(user.token), otp = new TOTP({ secret: setupTotp.secret });
    const codes = await service.confirmTotp({ token: user.token, code: otp.generate({ timestamp: now() }) });
    assert.equal(codes.recoveryCodes.length, 10);
    await assert.rejects(service.login({ email: user.user.email, password }), { code: 'invalid_credentials' });
    advance(30000);
    const current = otp.generate({ timestamp: now() });
    await service.login({ email: user.user.email, password, totp: current });
    await assert.rejects(service.login({ email: user.user.email, password, totp: current }), { code: 'invalid_credentials' });
    await service.login({ email: user.user.email, password, recoveryCode: codes.recoveryCodes[0]! });
    await assert.rejects(service.login({ email: user.user.email, password, recoveryCode: codes.recoveryCodes[0]! }), { code: 'invalid_credentials' });
    const reset = (await service.issueToken({ email: user.user.email, purpose: 'reset-password' })).token!;
    await service.resetPassword({ token: reset, password: password + ' changed' });
    await assert.rejects(service.login({ email: user.user.email, password: password + ' changed' }), { code: 'invalid_credentials' });
    await service.close();
    const bytes = await readFile(database);
    assert.equal(bytes.includes(Buffer.from(setupTotp.secret)), false);
    assert.equal(bytes.includes(Buffer.from(codes.recoveryCodes[0]!)), false);
});
test('a browser-binding check can peek a flow without spending it (#465)', async (t) => {
    const { service, now } = await setup(t);
    await service.putFlow({ id: 'peek-flow', kind: 'oidc', data: { verifier: 'synthetic-verifier', browserHash: 'right-browser' }, expires: now() + 60000 });
    // A caller (an HTTP handler checking browser binding before spending the flow) can read the
    // flow's data without consuming it: a request replayed from the wrong browser is rejected by
    // the caller's own binding check without burning the flow the right browser still needs.
    assert.deepEqual(await service.peekFlow('peek-flow', 'oidc'), { verifier: 'synthetic-verifier', browserHash: 'right-browser' });
    assert.deepEqual(await service.peekFlow('peek-flow', 'oidc'), { verifier: 'synthetic-verifier', browserHash: 'right-browser' });
    assert.deepEqual(await service.consumeFlow('peek-flow', 'oidc'), { verifier: 'synthetic-verifier', browserHash: 'right-browser' });
    assert.equal(await service.consumeFlow('peek-flow', 'oidc'), null);
    assert.equal(await service.peekFlow('peek-flow', 'oidc'), null);
});
test('encrypted flows are expiring and single-use, identities never auto-link and passkey counters compare atomically', async (t) => {
    const { service, now, advance } = await setup(t);
    await service.putFlow({ id: 'flow-1', kind: 'oidc', data: { verifier: 'synthetic-verifier', browserHash: 'binding' }, expires: now() + 60000 });
    const results = await Promise.all([service.consumeFlow('flow-1', 'oidc'), service.consumeFlow('flow-1', 'oidc')]);
    assert.equal(results.filter(Boolean).length, 1);
    await service.putFlow({ id: 'flow-2', kind: 'oidc', data: {}, expires: now() + 1000 });
    advance(1001);
    assert.equal(await service.consumeFlow('flow-2', 'oidc'), null);
    const user = await service.register({ email: 'link@example.com', password });
    await assert.rejects(service.createExternalAccount({ email: user.user.email, provider: 'google', subject: 'sub-1', emailVerified: true }), { code: 'explicit_identity_link_required' });
    await service.linkExternal({ sessionReference: sessionReference(user.token), provider: 'google', subject: 'sub-1' });
    assert.equal((await service.findExternal('google', 'sub-1'))?.id, user.user.id);
    const external = await service.createExternalAccount({ email: 'external@example.com', provider: 'google', subject: 'sub-2', emailVerified: true });
    await assert.rejects(service.login({ email: external.email, password }), { code: 'invalid_credentials' });
    assert.equal((await service.issueSession(external.id, { method: 'oidc', proof: (await service.getExternalProof('google', 'sub-2'))!.proof })).principal.id, external.id);
});
test('pending external proofs cannot survive factor reset, identity unlink or credential-version changes', async (t) => {
    const { service, now, advance } = await setup(t), user = await service.register({ email: 'stale-oidc@example.com', password });
    await service.linkExternal({ sessionReference: sessionReference(user.token),  provider: 'oidc', subject: 'bound' });
    const setupTotp = await service.beginTotp(user.token), otp = new TOTP({ secret: setupTotp.secret });
    await service.confirmTotp({ token: user.token, code: otp.generate({ timestamp: now() }) });
    const snapshot = (await service.getExternalProof('oidc', 'bound'))!;
    advance(30000);
    await service.disableTotp({ token: user.token, password, code: otp.generate({ timestamp: now() }) });
    await assert.rejects(service.issueSession(user.user.id, { method: 'oidc', proof: snapshot.proof }), { code: 'stale_auth_proof' });
    const linked = (await service.getExternalProof('oidc', 'bound'))!;
    await service.unlinkExternal({ token: user.token, provider: 'oidc', subject: 'bound' });
    await assert.rejects(service.issueSession(user.user.id, { method: 'oidc', proof: linked.proof }), { code: 'stale_auth_proof' });
});
test('passkey proof issuance atomically checks ownership, version and key while advancing counters once', async (t) => {
    const { service } = await setup(t), user = await service.register({ email: 'proof-key@example.com', password });
    await service.addPasskey({ actorToken: user.token, credential: { id: 'bound-key', publicKey: 'original-key', counter: 1 } });
    const proof = { ...(await service.getPasskey('bound-key'))!.proof, newCounter: 2 };
    const raced = await Promise.allSettled([service.issueSession(user.user.id, { method: 'passkey', proof }), service.issueSession(user.user.id, { method: 'passkey', proof })]);
    assert.equal(raced.filter(r => r.status === 'fulfilled').length, 1);
    assert.equal((await service.getPasskey('bound-key'))?.credential.counter, 2);
    const removed = { ...(await service.getPasskey('bound-key'))!.proof, newCounter: 3 };
    await service.removePasskey({ token: user.token, credentialId: 'bound-key' });
    await service.addPasskey({ actorToken: user.token, credential: { id: 'bound-key', publicKey: 'replacement-key', counter: 2 } });
    await assert.rejects(service.issueSession(user.user.id, { method: 'passkey', proof: removed }), { code: 'stale_auth_proof' });
});
test('passkey step-up uses the durable MFA attempt budget and refuses mismatched account proofs', async (t) => {
    const { service, now } = await setup(t), user = await service.register({ email: 'step-proof@example.com', password });
    await service.addPasskey({ actorToken: user.token, credential: { id: 'step-key', publicKey: 'public-key', counter: 0 } });
    const setupTotp = await service.beginTotp(user.token), otp = new TOTP({ secret: setupTotp.secret });
    const current = otp.generate({ timestamp: now() });
    await service.confirmTotp({ token: user.token, code: current });
    const proof = { ...(await service.getPasskey('step-key'))!.proof, newCounter: 1 };
    const wrong = current === '000000' ? '000001' : '000000';
    for (let index = 0; index < 10; index++)
        await assert.rejects(service.completeStepUp({ token: user.token, accountId: user.user.id, method: 'passkey', proof, totp: wrong }), { code: 'invalid_credentials' });
    await assert.rejects(service.completeStepUp({ token: user.token, accountId: user.user.id, method: 'passkey', proof, totp: wrong }), { code: 'authentication_rate_limited' });
    assert.equal((await service.getPasskey('step-key'))?.credential.counter, 0);
});
test('explicit passkey second factors lift enrollment only with independent ownership proof and are consumed atomically', async (t) => {
    const { service } = await setup(t, { allowPasskeySecondFactor: true, requireMfa: true });
    const user = await service.register({ email: 'factor-password@example.com', password });
    assert.deepEqual(user.principal.restrictions, ['enroll-mfa']);
    await service.addPasskey({ actorToken: user.token, credential: { id: 'factor-key', publicKey: 'synthetic-factor-public-key', counter: 0 } });
    const enrollment = await factorProof(service, 'factor-key');
    await service.setPasskeySecondFactor({ token: user.token, credentialId: 'factor-key', enabled: true, secondFactor: enrollment });
    assert.equal((await service.authenticate(user.token))?.restrictions, undefined);
    assert.equal((await service.getUser(user.user.id))?.passkeyMfaEnabled, true);
    assert.equal((await service.listPasskeys(user.user.id))[0]?.secondFactor, true);
    await assert.rejects(service.login({ email: user.user.email, password }), { code: 'second_factor_required' });
    const proof = await factorProof(service, 'factor-key');
    await assert.rejects(service.login({ email: user.user.email, password: 'incorrect password', secondFactor: proof }), { code: 'invalid_credentials' });
    await assert.rejects(service.login({ email: user.user.email, password, secondFactor: { ...proof, browserHash: '3'.repeat(64) } }), { code: 'invalid_second_factor' });
    const signed = await service.login({ email: user.user.email, password, secondFactor: proof });
    assert.ok(await service.authenticate(signed.token));
    await assert.rejects(service.login({ email: user.user.email, password, secondFactor: proof }), { code: 'invalid_second_factor' });
    await assert.rejects(service.setPasskeySecondFactor({ token: signed.token, credentialId: 'factor-key', enabled: false }), { code: 'last_required_factor' });
    const other = await service.register({ email: 'factor-other@example.com', password });
    await assert.rejects(service.login({ email: other.user.email, password, secondFactor: await factorProof(service, 'factor-key') }), { code: 'invalid_second_factor' });
});
test('the same passkey cannot be both primary and second factor, including restricted signup enrollment', async (t) => {
    const { service } = await setup(t, { allowPasskeySecondFactor: true, requireMfa: true });
    const browserHash = '4'.repeat(64), start = await service.beginSignup({ email: 'factor-passkey@example.com', browserHash }), binding = { flowId: start.flowId, browserHash }, challenge = 's'.repeat(43);
    await service.setSignupPasskeyChallenge({ ...binding, challenge });
    await service.setSignupPasskey({ ...binding, challenge, credential: { id: 'primary-key', publicKey: 'synthetic-primary-public', counter: 0 } });
    const account = (await service.completeSignup(binding))!;
    await assert.rejects(service.setPasskeySecondFactor({ token: account.token, credentialId: 'primary-key', enabled: true, secondFactor: await factorProof(service, 'primary-key') }), { code: 'independent_second_factor_required' });
    await service.addPasskey({ actorToken: account.token, credential: { id: 'independent-key', publicKey: 'synthetic-independent-public', counter: 0 } });
    await service.setPasskeySecondFactor({ token: account.token, credentialId: 'independent-key', enabled: true, secondFactor: await factorProof(service, 'independent-key') });
    const same = (await service.getPasskey('independent-key'))!, sameFactor = await factorProof(service, 'independent-key');
    await assert.rejects(service.issueSession(account.user.id, { method: 'passkey', proof: { ...same.proof, newCounter: same.credential.counter + 1 }, secondFactor: sameFactor }), { code: 'independent_second_factor_required' });
    const primary = (await service.getPasskey('primary-key'))!;
    assert.ok(await service.issueSession(account.user.id, { method: 'passkey', proof: { ...primary.proof, newCounter: 1 }, secondFactor: sameFactor }));
});
test('trusted-device exemptions are explicit, version-bound and never grant fresh administration or renew trust', async (t) => {
    const { service } = await setup(t, { allowPasskeySecondFactor: true, trustedDeviceTtlMs: 60000 });
    const admin = await service.bootstrapAdmin({ email: 'trust-admin@example.com', password }), target = await service.register({ email: 'trust-target@example.com', password });
    await assert.rejects(service.rememberDevice({ token: admin.token }), { code: 'fresh_second_factor_required' });
    await service.addPasskey({ actorToken: admin.token, credential: { id: 'trust-factor', publicKey: 'synthetic-trust-factor', counter: 0 } });
    await service.setPasskeySecondFactor({ token: admin.token, credentialId: 'trust-factor', enabled: true, secondFactor: await factorProof(service, 'trust-factor') });
    const trust = await service.rememberDevice({ token: admin.token, label: 'Synthetic browser' });
    const remembered = await service.login({ email: admin.user.email, password, trustedDevice: trust.token });
    assert.equal(remembered.principal.authenticatedAt, 0);
    assert.equal((await service.authenticate(remembered.token))?.authenticatedAt, 0);
    await assert.rejects(service.adminSetStatus({ actorToken: remembered.token, accountId: target.user.id, status: 'locked' }), { code: 'fresh_authentication_required' });
    await assert.rejects(service.rememberDevice({ token: remembered.token }), { code: 'fresh_authentication_required' });
    await assert.rejects(service.stepUp({ token: remembered.token, password }), { code: 'second_factor_required' });
    const devices = await service.listTrustedDevices(remembered.token);
    assert.equal(devices.length, 1);
    assert.equal(Object.hasOwn(devices[0]!, 'hash'), false);
    const stepped = await service.stepUp({ token: remembered.token, password, secondFactor: await factorProof(service, 'trust-factor') });
    assert.ok(stepped.principal.authenticatedAt > 0);
    await service.revokeTrustedDevice({ token: stepped.token, deviceId: devices[0]!.id });
    await assert.rejects(service.login({ email: admin.user.email, password, trustedDevice: trust.token }), { code: 'invalid_trusted_device' });
    const another = await service.rememberDevice({ token: stepped.token });
    await service.revokeSessions(admin.user.id);
    await assert.rejects(service.login({ email: admin.user.email, password, trustedDevice: another.token }), { code: 'invalid_trusted_device' });
});
test('passkey-only second-factor email recovery invalidates device trust and restricts enrollment to its recovery grant', async (t) => {
    const { service, advance } = await setup(t, { allowPasskeySecondFactor: true, allowEmailFactorRecovery: true, trustedDeviceTtlMs: 172800000 });
    const account = await service.register({ email: 'passkey-factor-recovery@example.com', password });
    await service.consumeVerification((await service.issueToken({ email: account.user.email, purpose: 'verify-email' })).token!, account.token);
    await service.addPasskey({ actorToken: account.token, credential: { id: 'lost-factor-key', publicKey: 'synthetic-lost-key', counter: 0 } });
    await service.setPasskeySecondFactor({ token: account.token, credentialId: 'lost-factor-key', enabled: true, secondFactor: await factorProof(service, 'lost-factor-key') });
    const trust = await service.rememberDevice({ token: account.token });
    const browserToken = 'r'.repeat(43), issued = await service.beginFactorRecovery({ email: account.user.email, browserToken });
    assert.ok(issued.verificationToken);
    await service.confirmFactorRecovery({ token: issued.verificationToken, browserToken });
    advance(86400001);
    const recovered = await service.completeFactorRecovery({ token: issued.verificationToken, browserToken });
    assert.deepEqual(recovered.principal.restrictions, ['enroll-mfa']);
    assert.equal((await service.getUser(account.user.id))?.passkeyMfaEnabled, undefined);
    assert.equal((await service.listTrustedDevices(recovered.token)).length, 0);
    const unproved = await service.login({ email: account.user.email, password, trustedDevice: trust.token });
    assert.deepEqual(unproved.principal.restrictions, ['enroll-mfa']);
    await assert.rejects(service.addPasskey({ actorToken: unproved.token, credential: { id: 'unproved-new-key', publicKey: 'synthetic', counter: 0 } }), { code: 'recovery_enrollment_proof_required' });
    await service.addPasskey({ actorToken: recovered.token, credential: { id: 'recovered-factor-key', publicKey: 'synthetic-recovered-key', counter: 0 } });
    await service.setPasskeySecondFactor({ token: recovered.token, credentialId: 'recovered-factor-key', enabled: true, secondFactor: await factorProof(service, 'recovered-factor-key') });
    assert.equal((await service.authenticate(recovered.token))?.restrictions, undefined);
    assert.equal(await service.authenticate(unproved.token), null);
    await assert.rejects(service.login({ email: account.user.email, password, trustedDevice: trust.token }), { code: 'invalid_trusted_device' });
});
test('factor proofs expire and trusted devices have bounded lifetimes, count and current-version MFA mint authority', async (t) => {
    const { service, options, advance } = await setup(t, { allowPasskeySecondFactor: true, trustedDeviceTtlMs: 60000 });
    const account = await service.register({ email: 'bounded-trust@example.com', password });
    await service.addPasskey({ actorToken: account.token, credential: { id: 'bounded-factor', publicKey: 'synthetic-bounded-key', counter: 0 } });
    await service.setPasskeySecondFactor({ token: account.token, credentialId: 'bounded-factor', enabled: true, secondFactor: await factorProof(service, 'bounded-factor') });
    const trusts = [];
    for (let n = 0; n < 20; n++)
        trusts.push(await service.rememberDevice({ token: account.token }));
    await assert.rejects(service.rememberDevice({ token: account.token }), { code: 'trusted_device_limit' });
    const oldProof = await factorProof(service, 'bounded-factor');
    advance(300001);
    await assert.rejects(service.login({ email: account.user.email, password, trustedDevice: trusts[0]!.token }), { code: 'invalid_trusted_device' });
    await assert.rejects(service.login({ email: account.user.email, password, secondFactor: oldProof }), { code: 'invalid_second_factor' });
    const fresh = await service.login({ email: account.user.email, password, secondFactor: await factorProof(service, 'bounded-factor') });
    await service.updateProfile({ token: fresh.token, profile: { displayName: 'Updated profile' } });
    await assert.rejects(service.rememberDevice({ token: fresh.token }), { code: 'fresh_second_factor_required' });
    await service.changePassword({ token: fresh.token, currentPassword: password, password: 'changed synthetic password 123', secondFactor: await factorProof(service, 'bounded-factor') });
    await assert.rejects(service.rememberDevice({ token: fresh.token }), { code: 'fresh_authentication_required' });
    await assert.rejects(createAuthService({ ...options, trustedDeviceTtlMs: 2592000001 }), { code: 'invalid_trusted_device_policy' });
});
test('independent passkey proof replaces a lost TOTP and works across OIDC and human-code primaries', async (t) => {
    const { service, now } = await setup(t, { allowPasskeySecondFactor: true, trustedDeviceTtlMs: 60000 });
    const account = await service.register({ email: 'multi-primary-factor@example.com', password });
    await verifyOwnMailbox(service, account.user.email, account.token);
    await service.linkExternal({ sessionReference: sessionReference(account.token),  provider: 'example-provider', subject: 'synthetic-subject' });
    await service.addPasskey({ actorToken: account.token, credential: { id: 'multi-primary-key', publicKey: 'synthetic-multi-primary-key', counter: 0 } });
    await service.setPasskeySecondFactor({ token: account.token, credentialId: 'multi-primary-key', enabled: true, secondFactor: await factorProof(service, 'multi-primary-key') });
    const setupTotp = await service.beginTotp(account.token), totp = new TOTP({ secret: setupTotp.secret });
    await service.confirmTotp({ token: account.token, code: totp.generate({ timestamp: now() }) });
    await service.disableTotp({ token: account.token, password, secondFactor: await factorProof(service, 'multi-primary-key') });
    assert.equal((await service.getUser(account.user.id))?.totpEnabled, false);
    assert.equal((await service.getUser(account.user.id))?.passkeyMfaEnabled, true);
    const primary = (await service.getExternalProof('example-provider', 'synthetic-subject'))!;
    await assert.rejects(service.issueSession(account.user.id, { method: 'oidc', proof: primary.proof, trustedDevice: 'z'.repeat(43) }), { code: 'invalid_trusted_device' });
    const signed = await service.issueSession(account.user.id, { method: 'oidc', proof: primary.proof, secondFactor: await factorProof(service, 'multi-primary-key') });
    const trust = await service.rememberDevice({ token: signed.token });
    const rememberedOidc = await service.issueSession(account.user.id, { method: 'oidc', proof: primary.proof, trustedDevice: trust.token });
    assert.equal(rememberedOidc.principal.authenticatedAt, 0);
    const code = await service.issueEmailCode({ email: account.user.email });
    const rememberedCode = await service.consumeEmailCode({ flowId: code.flowId, code: code.code!, trustedDevice: trust.token });
    assert.equal(rememberedCode.principal.authenticatedAt, 0);
    const next = await service.issueEmailCode({ email: account.user.email });
    const actual = await service.consumeEmailCode({ flowId: next.flowId, code: next.code!, secondFactor: await factorProof(service, 'multi-primary-key') });
    assert.ok(actual.principal.authenticatedAt > 0);
    assert.ok(await service.rememberDevice({ token: actual.token }));
});

test('method removal preserves an independent primary and passkey factor combination', async t => {
    const {service} = await setup(t, {allowPasskeySecondFactor:true});
    const admin = await service.bootstrapAdmin({email:'method-admin@example.test',password});
    const browserHash='4'.repeat(64), start=await service.beginSignup({email:'method-primary@example.test',browserHash}), binding={flowId:start.flowId,browserHash}, challenge='s'.repeat(43);
    await service.setSignupPasskeyChallenge({...binding,challenge});
    await service.setSignupPasskey({...binding,challenge,credential:{id:'primary-method',publicKey:'synthetic-primary-public',counter:0}});
    const account=(await service.completeSignup(binding))!;
    await service.addPasskey({actorToken:account.token,credential:{id:'factor-method',publicKey:'synthetic-factor-public',counter:0}});
    await service.setPasskeySecondFactor({token:account.token,credentialId:'factor-method',enabled:true,secondFactor:await factorProof(service,'factor-method')});
    await assert.rejects(service.removePasskey({token:account.token,credentialId:'primary-method'}),{code:'last_sign_in_method'});
    const base={actorToken:admin.token,accountIds:[account.user.id],reason:'Reviewed method removal'};
    await assert.rejects(service.stageAccountAdministration({...base,action:'remove-passkey',credentialId:'primary-method'}),{code:'last_sign_in_method'});
    await service.linkExternal({ sessionReference: sessionReference(account.token), provider:'example',subject:'synthetic-subject'});
    await service.removePasskey({token:account.token,credentialId:'primary-method'});
    await assert.rejects(service.unlinkExternal({token:account.token,provider:'example',subject:'synthetic-subject'}),{code:'last_sign_in_method'});
    const methods=await service.inspectAccountAuthentication({actorToken:admin.token,accountId:account.user.id,reason:'Review remaining methods'});
    await assert.rejects(service.stageAccountAdministration({...base,action:'remove-external',externalId:methods.external[0]!.id}),{code:'last_sign_in_method'});
    assert.ok(await service.getPasskey('factor-method'));
});
