import { cleanup } from './cleanup.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { createAuthPreset } from '../src/presets.ts';
import { createAuthService } from '../src/auth-core.ts';
import { activatedUi } from './support/render.ts';
import { withCompanions, companions } from './support/companions.ts';
const base = { origin: 'https://site.example', rpName: 'Site' };
test('operator presets wire capabilities and refuse incomplete hardened configuration', () => {
    const standard = createAuthPreset(base);
    assert.equal(standard.service.requireMfa, false);
    assert.equal(standard.service.deletionGraceMs, 7 * 86400000);
    assert.ok(standard.extension.passkeys);
    assert.deepEqual(Object.keys(standard.extension), ['passkeys']);
    assert.equal(standard.notices.length, 0);
    assert.throws(() => createAuthPreset({ ...base, preset: 'hardened' }), /requires password breach screening/);
    const checkPassword = async () => { }, hardened = createAuthPreset({ ...base, preset: 'hardened', checkPassword });
    assert.equal(hardened.service.requireMfa, true);
    assert.equal(hardened.service.requireEmailVerification, true);
    assert.equal(hardened.service.checkPassword, checkPassword);
    assert.equal(hardened.service.deletionGraceMs, 30 * 86400000);
    assert.ok(hardened.service.sessionTtlMs! < standard.service.sessionTtlMs!);
    assert.equal(hardened.notices.length, 0);
    assert.throws(() => createAuthPreset({ ...base, origin: 'http://site.example' }), /HTTPS/);
});
test('hardened auth refuses to activate without mail delivery and activates with it', async (t) => {
    const root = await mkdtemp(join(tmpdir(), 'urlcode-auth-preset-'));
    cleanup(t, () => rm(root, { recursive: true, force: true }));
    const preset = createAuthPreset({ ...base, preset: 'hardened', checkPassword: async () => { } });
    const service = await createAuthService({ database: join(root, 'accounts.sqlite'), encryptionKey: randomBytes(32), roles: { member: [] }, defaultRole: 'member', registrationMode: 'open', ...preset.service });
    cleanup(t, () => service.close());
    const projectSha256 = 'a'.repeat(64), ui = await activatedUi(t, import.meta.dirname, projectSha256, base.origin);
    const context = { origin: base.origin, target: 'node' as const, projectSha256, mounts: ['/account'], root: import.meta.dirname };
    const without = withCompanions(await companions(t, root, projectSha256, base.origin, { transport: false }));
    await assert.rejects(Promise.resolve(without({ service, csrfKey: randomBytes(32), projectSha256, ui, ...preset.extension }).activate({ registration: 'open' }, context)), /hardened auth needs mail delivery/);
    const withMail = withCompanions(await companions(t, root, projectSha256, base.origin));
    const instance = await withMail({ service, csrfKey: randomBytes(32), projectSha256, ui, ...preset.extension }).activate({ registration: 'open' }, context);
    await instance.close?.();
});
