import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname,resolve as resolvePath} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
// Resolve the CLI rather than assuming a package-local node_modules: as a
// workspace under the core repository, npm hoists shared devDependencies to the
// root, so the hardcoded path this used to carry does not exist here. The
// package exports only its own package.json, so go through that and read the
// bin entry rather than reaching past the export map.
const require=createRequire(import.meta.url);
const cliManifest=require.resolve('@tailwindcss/cli/package.json');
const cli=resolvePath(dirname(cliManifest),require(cliManifest).bin.tailwindcss);
mkdirSync(root+'.build',{recursive:true});

// Both the shared `stylesheet` export and the kit's own `kitCss` compile from
// Tailwind so there is one source of truth (styles/*.css) instead of one
// generated and one hand-written stylesheet. Each source names its own
// generated module and exported constant.
const targets=[
    {source:'styles/tailwind.css',out:'src/styles.generated.ts',exportName:'stylesheet',build:'.build/ui.css'},
    {source:'styles/kit.css',out:'src/kit-styles.generated.ts',exportName:'kitCss',build:'.build/kit.css'},
];
for(const target of targets){
    execFileSync(process.execPath,[cli,'-i',root+target.source,'-o',root+target.build,'--minify'],{cwd:root,stdio:'inherit'});
    const css=readFileSync(root+target.build,'utf8');
    if(/<\/style/i.test(css))throw new Error('Unsafe stylesheet output: '+target.source);
    writeFileSync(root+target.out,'// Generated by scripts/build-styles.mjs; do not edit.\nexport const '+target.exportName+': string = '+JSON.stringify(css)+';\n');
}
rmSync(root+'.build',{recursive:true,force:true});
