import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname,resolve as resolvePath} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
// Resolve the CLI rather than assuming a package-local node_modules: as a
// workspace under the core repository, npm hoists shared devDependencies to the
// root, so the hardcoded path this used to carry does not exist here. The
// package exports only its own package.json, so go through that and read the
// bin entry rather than reaching past the export map.
const require=createRequire(import.meta.url);
const cliManifest=require.resolve('@tailwindcss/cli/package.json');
const cli=resolvePath(dirname(cliManifest),require(cliManifest).bin.tailwindcss);
mkdirSync(root+'.build',{recursive:true});
execFileSync(process.execPath,[cli,'-i',root+'styles/tailwind.css','-o',root+'.build/ui.css','--minify'],{cwd:root,stdio:'inherit'});
const css=readFileSync(root+'.build/ui.css','utf8');
if(/<\/style/i.test(css))throw new Error('Unsafe stylesheet output');
writeFileSync(root+'src/styles.generated.ts','// Generated by scripts/build-styles.mjs; do not edit.\nexport const stylesheet: string = '+JSON.stringify(css)+';\n');
rmSync(root+'.build',{recursive:true,force:true});
