import {escapeHtml,icon,hiddenField,postForm} from '@jimhoyd/urlcode-ui';
import type {AuthAccount,AuthUser} from '@jimhoyd/urlcode-auth';
import type {AdminCopy} from './admin-copy.ts';
import {nextPage,observedLastSeen,userFilterFields,userFilterKeys} from './admin-reporting.ts';
import {formField,markup} from './admin-ui.ts';
import type {Screen} from './admin-ui.ts';

/** Account workflows and authority stay here; URLCode UI supplies only generic visual primitives. */
export function userDirectory(input:{users:AuthUser[];next?:string;query:URLSearchParams;account:AuthAccount;mount:string;csrf:string;copy:AdminCopy;canSendSetup:boolean}):Screen {
 const {users,query,account,mount,csrf,copy}=input;
 const text=(source:string)=>copy.s(source),html=(source:string)=>escapeHtml(text(source));
 const tr=(key:string,values?:Record<string,string|number>)=>copy.t(key,values),trh=(key:string,values?:Record<string,string|number>)=>escapeHtml(tr(key,values));
 const field=(name:string,label:string,type='text')=>formField(name,text(label),type);
 const form=(path:string,fields:string,label:string,destructive=false)=>postForm({action:mount+path,csrf,fields,label:text(label),destructive,className:'ui-form-grid'});
 const manage=account.has('auth.users.manage'),sessions=account.has('auth.sessions.manage'),select=manage||sessions;
 const setup=input.canSendSetup&&account.has('auth.users.create')?{summary:text('Create account'),form:markup(form('/users/create',field('email','Email address','email')+field('reason','Reason'),'Send setup link'))}:null;
 const filters=`<form method="get" action="${escapeHtml(mount+'/users')}">${userFilterFields(query,text)}<div class="ui-toolbar"><button type="submit">${icon('search')}<span>${trh('admin.users.filter.apply')}</span></button><a href="${escapeHtml(mount+'/users'+(query.get('lang')?'?lang='+encodeURIComponent(query.get('lang')!):''))}">${html('Reset filters')}</a></div></form>`;
 const exports=account.has('auth.users.export')?{summary:markup(icon('download')+`<span>${html('Export accounts')}</span>`),forms:markup(form('/users/export-page',[...userFilterKeys,'after'].map(key=>hiddenField(key,query.get(key)||'')).join('')+field('reason','Reason')+`<p class="ui-muted">${trh('admin.copy.exportThisFilteredPageOnlyAtMost50AccountsEmailAddressesStayMasked')}</p>`,'Export page (CSV)')+form('/users/export-range',userFilterKeys.map(key=>hiddenField(key,query.get(key)||'')).join('')+field('reason','Reason')+`<p class="ui-muted">${html('Complete export: at most 5,000 accounts, 4 MiB and 5 seconds. Narrow filters if the limit is exceeded.')}</p>`,'Export all (CSV)'))}:null;
 const bulk=select?{summary:tr('admin.copy.bulkAction'),form:markup(`<form class="ui-form-grid" id="bulk-users" method="post" action="${escapeHtml(mount+'/users/bulk')}">${hiddenField('csrf',csrf)}<label>${trh('admin.copy.bulkAction')}<select name="action">${manage?`<option value="lock">${trh('admin.copy.lock')}</option><option value="unlock">${trh('admin.copy.unlock')}</option>`:''}${sessions?`<option value="revoke-sessions">${trh('admin.action.revokeSessions')}</option>`:''}</select></label>${field('reason','Reason')}${field('confirmation','Type LOCK, UNLOCK or REVOKE-SESSIONS followed by a space and the selected count')}<p class="ui-muted">${trh('admin.copy.selectAccountsInTheTableAllSelectedAccountsMustBePermittedOtherwiseNoneAreChanged')}</p><button class="ui-button-destructive" type="submit">${trh('admin.copy.applyBulkAction')}</button></form>`)}:null;
 const rows=users.map(user=>`<tr><td>${user.id!==account.id&&user.status!=='pending-delete'&&select?`<input type="checkbox" form="bulk-users" name="selected.${escapeHtml(user.id)}" value="yes" aria-label="${trh('admin.action.selectAccount',{account:user.email})}">`:''}</td><td><a href="${escapeHtml(mount+'/users/detail?id='+encodeURIComponent(user.id))}"><strong>${escapeHtml(user.email)}</strong></a><small class="ui-muted ui-account-id">${escapeHtml(user.id)}</small></td><td><span class="ui-badge" data-status="${escapeHtml(user.status)}">${html(({active:'Active',locked:'Locked','pending-delete':'Pending deletion'} as Record<string,string>)[user.status]??user.status)}</span></td><td class="ui-muted">${observedLastSeen(user)?`<time datetime="${escapeHtml(observedLastSeen(user))}">${escapeHtml(observedLastSeen(user).replace('T',' ').slice(0,16)+' UTC')}</time>`:'—'}</td><td>${user.roles.map(role=>`<span class="ui-badge">${escapeHtml(role)}</span>`).join(' ')}</td><td>${manage&&user.id!==account.id&&user.status!=='pending-delete'?`<details><summary>${html(user.status==='active'?'Lock account':'Unlock account')}</summary>${form('/users/status',hiddenField('accountId',user.id)+hiddenField('status',user.status==='active'?'locked':'active')+field('reason','Reason'),user.status==='active'?'Lock account':'Unlock account',user.status==='active')}</details>`:''}</td></tr>`).join('');
 return {name:'admin/users',view:{setup,filters:markup(filters),heading:tr('admin.nav.users'),count:tr('admin.number.value',{value:users.length}),caption:tr('admin.copy.accountsEmailAddressesMasked'),columns:{select:tr('admin.copy.select'),account:tr('admin.nav.account'),status:tr('admin.copy.status'),lastSeen:tr('admin.users.filter.lastSeen'),roles:tr('admin.nav.roles'),actions:tr('admin.copy.actions')},rows:markup(rows),empty:text('No matching accounts. Try changing your filters.'),caveat:tr('admin.users.filter.activityCaveat'),nextHref:input.next?nextPage(mount+'/users',query,input.next,userFilterKeys):null,nextLabel:tr('action.next'),bulk,exports}};
}
