/**
 * The console's copy. Admin contributes this catalogue to the ui extension (`contributes.ui.sources`), so every string
 * is an `admin.*` key a project can translate or override in `ui/copy/<locale>.json`. Auth's catalogue carries no
 * console copy, and admin reads no auth key: it resolves only `admin.*` keys and the kit's own (`ui.*`, `nav.skip`,
 * `action.next`, `action.previous`, `message.empty`).
 */
import type {Catalogue,PresentationContext} from '@jimhoyd/urlcode-ui';
export const adminCatalogue:Readonly<Catalogue>=Object.freeze({
 "admin.action.approveAccount":"Approve account",
 "admin.action.approveAndApply":"Approve and apply",
 "admin.action.closeWithoutApplying":"Close without applying",
 "admin.action.confirm":"Confirm identity",
 "admin.action.createCaseForASecondAdministrator":"Create case for a second administrator",
 "admin.action.exportAudit":"Export audit range as JSON",
 "admin.action.exportData":"Export account data",
 "admin.action.findSessions":"Find sessions",
 "admin.action.lock":"Lock account",
 "admin.action.revokeAllSessions":"Revoke all sessions",
 "admin.action.revokeSessions":"Revoke sessions",
 "admin.action.revokeThisSession":"Revoke this session",
 "admin.action.selectAccount":"Select {account}",
 "admin.action.sendInvitation":"Send invitation",
 "admin.action.startTenMinuteSupportImpersonation":"Start ten-minute support impersonation",
 "admin.action.unlock":"Unlock account",
 "admin.copy.accountsEmailAddressesMasked":"Accounts (email addresses masked)",
 "admin.copy.action":"Action",
 "admin.copy.actions":"Actions",
 "admin.copy.actor":"Actor",
 "admin.copy.applyBulkAction":"Apply bulk action",
 "admin.copy.authenticationMethodsOverTheSame30Days":"Authentication methods over the same 30 days",
 "admin.copy.authenticatorEnabled":"Authenticator enabled",
 "admin.copy.bulkAction":"Bulk action",
 "admin.copy.created":"Created",
 "admin.copy.dailyAuthenticationCounts":"Daily authentication counts",
 "admin.copy.email":"Email",
 "admin.copy.emailVerified":"Email verified",
 "admin.copy.exportThisFilteredPageOnlyAtMost50AccountsEmailAddressesStayMasked":"Export this filtered page only, at most 50 accounts. Email addresses stay masked.",
 "admin.copy.failedSignIns":"Failed sign-ins",
 "admin.copy.filterAudit":"Filter audit",
 "admin.copy.language":"Language",
 "admin.copy.lock":"Lock",
 "admin.copy.method":"Method",
 "admin.copy.recentEvents":"Recent events",
 "admin.copy.recentSecurityEvents":"Recent security events",
 "admin.copy.recordedAccountCreationsSuccessfulSignInsAndFailedSignInsTheseFiguresDescribeAuthenticationActivityDeploymentH":"Recorded account creations, successful sign-ins and failed sign-ins. These figures describe authentication activity; deployment health is not measured here.",
 "admin.copy.roleDefinitionsAreReadOnlyHere":"Role definitions are read-only here.",
 "admin.copy.select":"Select",
 "admin.copy.selectAccountsInTheTableAllSelectedAccountsMustBePermittedOtherwiseNoneAreChanged":"Select accounts in the table. All selected accounts must be permitted; otherwise none are changed.",
 "admin.copy.selectASectionOnlyPermittedOperationsAreShownConfigurationRemainsInVersionControlledProjectFiles":"Select a section. Only permitted operations are shown. Configuration remains in version-controlled project files.",
 "admin.copy.signIns":"Sign-ins",
 "admin.copy.signUps":"Sign-ups",
 "admin.copy.status":"Status",
 "admin.copy.subject":"Subject",
 "admin.copy.time":"Time",
 "admin.copy.unlock":"Unlock",
 "admin.copy.uTCDay":"UTC day",
 "admin.copy.viewAccountAudit":"View account audit",
 "admin.error.accountNotFound":"Account not found",
 "admin.error.aReasonIsRequired":"A reason is required",
 "admin.error.confirmYourIdentityBeforeThisAction":"Confirm your identity before this action",
 "admin.error.getHeadOrPostRequired":"GET, HEAD or POST required",
 "admin.error.httpDuplicateFilter":"Duplicate filter",
 "admin.error.httpExportExceedsOnePage":"Export exceeds one page",
 "admin.error.httpInvalidSelection":"Invalid selection",
 "admin.error.httpInvalidTimeRange":"Invalid time range",
 "admin.error.httpSelectBetweenOneAndFiftyDistinctAccounts":"Select between one and fifty distinct accounts",
 "admin.error.httpUseAUTCDateAndTimeEndingInZ":"Use a UTC date and time ending in Z",
 "admin.error.httpUseOneSelectionFormat":"Use one selection format",
 "admin.error.invalidBulkAction":"Invalid bulk action",
 "admin.error.invalidCaseAction":"Invalid case action",
 "admin.error.invalidStatus":"Invalid status",
 "admin.error.notFound":"Not found",
 "admin.error.pOSTRequired":"POST required",
 "admin.error.serviceUnavailable":"Service unavailable",
 "admin.error.typedConfirmationMustMatchTheActionAndSelectedCount":"Typed confirmation must match the action and selected count",
 "admin.field.accountId":"Account ID",
 "admin.field.caseAction":"Action: reset-factors, lock, unlock or roles",
 "admin.field.caseRoles":"Roles (for roles action)",
 "admin.field.email":"Email address",
 "admin.field.password":"Password",
 "admin.field.role":"Role name",
 "admin.field.roles":"Role names separated by commas",
 "admin.field.typeLOCKUNLOCKOrREVOKESESSIONSFollowedByASpaceAndTheSelectedCount":"Type LOCK, UNLOCK or REVOKE-SESSIONS followed by a space and the selected count",
 "admin.health.alerts":"Alerts",
 "admin.health.component":"Component",
 "admin.health.degraded":"Degraded",
 "admin.health.healthy":"Healthy",
 "admin.health.provider":"Identity provider",
 "admin.health.readiness":"Readiness",
 "admin.health.routes":"Routes",
 "admin.health.runtime":"Runtime",
 "admin.health.sender":"Email delivery",
 "admin.health.status":"Status",
 "admin.health.unavailable":"No operator health integration is configured.",
 "admin.health.unavailableStatus":"Unavailable",
 "admin.health.unknown":"Unknown",
 "admin.health.updated":"Last checked",
 "admin.health.version":"Runtime version",
 "admin.message.adminTotals":"{users} accounts; {locked} locked; {pending} pending deletion; {sessions} sessions; {waitlist} waiting for approval.",
 "admin.message.bulkUpdated":{"one":"{count} account updated.","other":"{count} accounts updated."},
 "admin.message.operationCompleted":"The operation completed.",
 "admin.message.permissionRequired":"Permission required",
 "admin.message.sessionsOnPage":{"one":"{count} session on this page.","other":"{count} sessions on this page."},
 "admin.nav.account":"Account",
 "admin.nav.audit":"Audit",
 "admin.nav.cases":"Cases",
 "admin.nav.health":"Service health",
 "admin.nav.overview":"Overview",
 "admin.nav.registration":"Registration",
 "admin.nav.roles":"Roles",
 "admin.nav.sessions":"Sessions",
 "admin.nav.users":"Users",
 "admin.number.value":"{value}",
 "admin.ops.action.assignRoles":"Assign roles",
 "admin.ops.action.cancelDeletion":"Cancel scheduled deletion",
 "admin.ops.action.forcePasswordReset":"Invalidate password and send setup link",
 "admin.ops.action.removeExternal":"Remove external sign-in method",
 "admin.ops.action.removePasskey":"Remove passkey",
 "admin.ops.action.requestEmailChange":"Request email change with 24-hour delay",
 "admin.ops.action.resendVerification":"Resend verification",
 "admin.ops.action.scheduleDeletion":"Schedule deletion with cancellation notice",
 "admin.ops.action.verifyEmail":"Verify email by human review",
 "admin.ops.actionLabel":"Action",
 "admin.ops.affected":"{count} accounts updated",
 "admin.ops.apply":"Deliver notices and apply",
 "admin.ops.bulkConfirm":"Type ACTION COUNT (for example ASSIGN-ROLES 2)",
 "admin.ops.bulkInfo":"Apply role assignment or resend verification to at most 50 accounts. Delivery must succeed before changes apply.",
 "admin.ops.completed":"Account administration completed",
 "admin.ops.confirm":"Type {value} to confirm",
 "admin.ops.email":"Requested new email address",
 "admin.ops.factorCase":"Reset factors through a two-administrator case",
 "admin.ops.ids":"Account IDs (comma-separated, maximum 50)",
 "admin.ops.info":"Actions require fresh administrator authentication and a reason. Notification delivery occurs before changes apply.",
 "admin.ops.no":"No",
 "admin.ops.passkey":"Passkey",
 "admin.ops.password":"Password configured",
 "admin.ops.reason":"Reason",
 "admin.ops.roles":"Roles (comma-separated)",
 "admin.ops.secondFactor":"Enrolled second factor",
 "admin.ops.title":"Account administration",
 "admin.ops.totp":"Authenticator configured",
 "admin.ops.yes":"Yes",
 "admin.page.accountDetails":"Account details",
 "admin.page.admin":"Administration",
 "admin.page.bulkUpdateCompleted":"Bulk update completed",
 "admin.page.error":"Request could not be completed",
 "admin.page.registrations":"Registration requests",
 "admin.page.signInMethods":"Sign-in methods",
 "admin.page.supportCases":"Support cases",
 "admin.page.updateCompleted":"Update completed",
 "admin.recovery.account":"Account",
 "admin.recovery.accountId":"Account ID",
 "admin.recovery.addNote":"Add note",
 "admin.recovery.address":"Approved replacement address",
 "admin.recovery.approval":"Independent approval reason",
 "admin.recovery.approve":"Approve and send restoration link",
 "admin.recovery.boundedEvidence":"Evidence assessment (maximum 2000 characters)",
 "admin.recovery.close":"Close without restoring access",
 "admin.recovery.closure":"Closure reason",
 "admin.recovery.confirmation":"Type RESTORE to confirm",
 "admin.recovery.create":"Open case for independent review",
 "admin.recovery.evidence":"Evidence assessment",
 "admin.recovery.intro":"Internal human review only. Do not enter passwords, tokens, identity document images or other unnecessary sensitive data. A distinct authorized administrator must independently review the evidence. References are plain text and are never fetched.",
 "admin.recovery.none":"None",
 "admin.recovery.note":"Internal case note",
 "admin.recovery.reason":"Reason",
 "admin.recovery.reference":"Internal evidence reference",
 "admin.recovery.state.cancelled":"Cancelled",
 "admin.recovery.state.delivery":"Awaiting delivery",
 "admin.recovery.state.ready":"Ready for restoration",
 "admin.recovery.state.redeemed":"Restored",
 "admin.recovery.state.review":"Awaiting independent review",
 "admin.recovery.status":"Status",
 "admin.recovery.title":"Manual account recovery",
 "admin.recovery.verifiedAddress":"Human-verified replacement email",
 "admin.text.accountIdentifier":"Account identifier",
 "admin.text.accounts":"Accounts",
 "admin.text.accountSections":"Account sections",
 "admin.text.activeAccounts":"Active accounts",
 "admin.text.activity":"Activity",
 "admin.text.added":"Added",
 "admin.text.administratorNote":"Administrator note",
 "admin.text.administratorNotes":"Administrator notes",
 "admin.text.administratorNoteSaved":"Administrator note saved.",
 "admin.text.auditPaginationUnavailable":"Audit pagination unavailable",
 "admin.text.auditPermissionIsRequired":"Audit permission is required.",
 "admin.text.auditRangeWasPrunedDuringExport":"Audit range was pruned during export",
 "admin.text.authenticationActivity":"Authentication activity",
 "admin.text.changeConsoleWordingThroughTheAdmin":"Change console wording through the admin.* keys of the UI catalogue.",
 "admin.text.chooseARangeThatHasStarted":"Choose a range that has started",
 "admin.text.chooseASmallerAuditRange":"Choose a smaller audit range",
 "admin.text.chooseBothUtcRangeEndpoints":"Choose both UTC range endpoints",
 "admin.text.consentRecord":"Consent record",
 "admin.text.data":"Data",
 "admin.text.eventSource":"Event source",
 "admin.text.invalidAccountAction":"Invalid account action",
 "admin.text.invalidAuditOrder":"Invalid audit order",
 "admin.text.invalidTime":"Invalid time",
 "admin.text.invalidVerificationFilter":"Invalid verification filter",
 "admin.text.lastUsed":"Last used",
 "admin.text.lockedAccounts":"Locked accounts",
 "admin.text.newestFirst":"Newest first",
 "admin.text.noteSaved":"Note saved",
 "admin.text.notRecorded":"Not recorded",
 "admin.text.oldestFirst":"Oldest first",
 "admin.text.oneAccountIdRequired":"One account ID required",
 "admin.text.order":"Order",
 "admin.text.overrideOneAdminScreenWhenIts":"Override one admin/* screen when its structure must change; keep permissions and mutation behavior package-owned.",
 "admin.text.passkeySecondFactorEnabled":"Passkey second factor enabled",
 "admin.text.rangeExportsStartAtTheBeginning":"Range exports start at the beginning of the selected range",
 "admin.text.recovery":"Recovery",
 "admin.text.recoveryContactsAreNotSupportedIn":"Recovery contacts are not supported in this release. Manual evidence requires independent operator assessment.",
 "admin.text.revealEmailAddress":"Reveal email address",
 "admin.text.saveAdministratorNote":"Save administrator note",
 "admin.text.securityCases":"Security cases",
 "admin.text.sequence":"Sequence",
 "admin.text.sessionManagementPermissionIsRequired":"Session management permission is required.",
 "admin.text.source":"Source",
 "admin.text.theAdministrationConsoleIsPartOf":"The administration console is part of the application, while auth keeps ownership of permissions, freshness checks, lifecycle hooks and transactional account operations, and audit keeps the log. Customize the console copy and screens before replacing behavior.",
 "admin.text.theExportCouldNotBeRecorded":"The export could not be recorded",
 "admin.text.typedConfirmationMustBeRestore":"Typed confirmation must be RESTORE",
 "admin.text.typedConfirmationMustMatchActionAnd":"Typed confirmation must match action and count",
 "admin.text.unknownAuditFilter":"Unknown audit filter",
 "admin.text.unknownDevice":"Unknown device",
 "admin.text.unknownSessionFilter":"Unknown session filter",
 "admin.text.unknownUserFilter":"Unknown user filter",
 "admin.text.waitingForApproval":"Waiting for approval",
 "admin.ui.accountActions":"Account actions",
 "admin.ui.action":"Event action",
 "admin.ui.activityDetails":"View activity totals",
 "admin.ui.activityPeriod":"Last 30 days",
 "admin.ui.actor":"Actor account ID",
 "admin.ui.advancedFilters":"Advanced filters",
 "admin.ui.auditExport":"Export audit events",
 "admin.ui.auditFilters":"Filter audit events",
 "admin.ui.auditIntro":"Review recorded security events. Use filters to narrow the time range or account.",
 "admin.ui.chartDescription":"Thirty UTC days of sign-ups, sign-ins and failed sign-ins. Failed sign-ins use a dashed line. Exact values follow in the daily table.",
 "admin.ui.confirmFresh":"Sensitive actions require a recent sign-in and a reason.",
 "admin.ui.createAccount":"Create account",
 "admin.ui.createCase":"Create a support case",
 "admin.ui.device":"Device",
 "admin.ui.expires":"Expires",
 "admin.ui.exportAccounts":"Export accounts",
 "admin.ui.exportAll":"Export all (CSV)",
 "admin.ui.exportPage":"Export page (CSV)",
 "admin.ui.from":"From UTC (YYYY-MM-DDTHH:mmZ)",
 "admin.ui.healthIntro":"Reported observations from this host and its configured integrations.",
 "admin.ui.methodIntro":"Review sign-in methods before changing account access.",
 "admin.ui.noAccounts":"No matching accounts. Try changing your filters.",
 "admin.ui.noActivity":"No account activity recorded.",
 "admin.ui.noAlerts":"No alerts reported.",
 "admin.ui.noAudit":"No audit events match these filters.",
 "admin.ui.noCases":"No support cases to review.",
 "admin.ui.noGrants":"No additional permissions",
 "admin.ui.noMethods":"No passkeys or external sign-in methods recorded.",
 "admin.ui.noNotes":"No administrator notes yet.",
 "admin.ui.noRecovery":"No manual recovery cases to review.",
 "admin.ui.noRegistrations":"No registration requests are waiting for approval.",
 "admin.ui.noSessions":"No active sessions match these filters.",
 "admin.ui.noteHelp":"Notes are recorded in the audit trail. Do not include credentials or recovery secrets.",
 "admin.ui.noTerms":"No consent record is stored for this account.",
 "admin.ui.noticePresentation":"The configured presentation needs an update.",
 "admin.ui.noticeProvider":"A provider credential is approaching expiry.",
 "admin.ui.noticeSender":"Notification sender reported a failure.",
 "admin.ui.noticeTranslation":"Some translations are incomplete.",
 "admin.ui.permissions":"Permissions",
 "admin.ui.resetFilters":"Reset filters",
 "admin.ui.returnOverview":"Return to overview",
 "admin.ui.returnUsers":"Back to users",
 "admin.ui.reviewCase":"Review case",
 "admin.ui.revokeExplanation":"The user can sign in again unless their account is locked.",
 "admin.ui.rolesIntro":"Review the permissions each role grants. Assign reviewed roles to an account below.",
 "admin.ui.searchAccounts":"Search accounts",
 "admin.ui.searchPlaceholder":"Email, name or account ID",
 "admin.ui.sendSetup":"Send setup link",
 "admin.ui.sessionFilters":"Filter sessions",
 "admin.ui.sessionIntro":"Review active sessions. Revoking a session signs that device out.",
 "admin.ui.subject":"Subject account ID",
 "admin.ui.to":"To UTC (YYYY-MM-DDTHH:mmZ)",
 "admin.users.exportAll":"Export all matching accounts as CSV",
 "admin.users.exportLimits":"Complete export: at most 5,000 accounts, 4 MiB and 5 seconds. Narrow filters if the limit is exceeded.",
 "admin.users.filter.active":"Active",
 "admin.users.filter.activityCaveat":"Last seen uses retained device and session activity; it is not a complete activity history.",
 "admin.users.filter.anyStatus":"Any status",
 "admin.users.filter.anyStoredMethod":"Any stored credential method",
 "admin.users.filter.anyVerification":"Any verification",
 "admin.users.filter.apply":"Apply filters",
 "admin.users.filter.ascending":"Ascending",
 "admin.users.filter.createdFrom":"Created from UTC",
 "admin.users.filter.createdTo":"Created to UTC",
 "admin.users.filter.descending":"Descending",
 "admin.users.filter.direction":"Direction",
 "admin.users.filter.displayName":"Display name",
 "admin.users.filter.external":"External identity",
 "admin.users.filter.lastSeen":"Last seen",
 "admin.users.filter.locale":"Locale",
 "admin.users.filter.locked":"Locked",
 "admin.users.filter.method":"Sign-in method",
 "admin.users.filter.pendingDelete":"Pending deletion",
 "admin.users.filter.search":"Search email, masked email, name or account ID",
 "admin.users.filter.seenFrom":"Last seen from UTC",
 "admin.users.filter.seenTo":"Last seen to UTC",
 "admin.users.filter.sort":"Sort by",
 "admin.users.filter.storedMethod":"Stored credential method",
 "admin.users.filter.unverified":"Unverified",
 "admin.users.filter.verification":"Email verification",
 "admin.users.filter.verified":"Verified",
});
/** The kit keys admin may read besides its own. */
const kitKeys=new Set(['nav.skip','action.next','action.previous','message.empty']);
const byEnglish=new Map<string,string>();
for(const [key,value]of Object.entries(adminCatalogue))if(typeof value==='string'&&!byEnglish.has(value))byEnglish.set(value,key);
/** Test hook: hears English text the console resolved that the admin catalogue does not carry (shown untranslated). */
export const copyObserver:{missing?:((source:string)=>void)|undefined}={};
export interface AdminCopy {
 readonly context:PresentationContext;
 /** An `admin.*` key (or a kit key), through the request's resolved catalogue. */
 t(key:string,values?:Readonly<Record<string,string|number>>):string;
 /** English source text the admin catalogue carries, through its `admin.*` key; anything else is shown as given. */
 s(source:string):string;
}
export function adminCopy(context:PresentationContext):AdminCopy {
 return Object.freeze({
  context,
  t(key:string,values?:Readonly<Record<string,string|number>>){
   if(!key.startsWith('admin.')&&!key.startsWith('ui.')&&!kitKeys.has(key))throw new Error(`Admin copy reads only admin.* and kit keys: ${key.slice(0,64)}`);
   return context.text(key,values);
  },
  s(source:string){
   const key=byEnglish.get(source);
   if(key)return context.text(key);
   copyObserver.missing?.(source);
   return source;
  },
 });
}
