// explainError's rule table (agent-context.ts), kept in its own module so it can be checked without
// widening the public @jimhoyd/urlcode/agent-context surface. Every nextTools entry is a canonical
// MCP tool name (mcp.ts canonicalMcpToolNames), never a pre-#590 legacy alias.
// Ordered: the first rule whose pattern matches the supplied text wins, so
// specific messages come before the families that contain them. Patterns
// follow the runtime's own error text; keep them in step when a message changes.
export const errorRules:readonly {id:string;pattern:RegExp;guidance:string;nextTools:readonly string[]}[]=[
  {id:'duplicate-key',pattern:/duplicate yaml|duplicate key/,guidance:'Give every mapping key one value. URLCode rejects duplicate YAML keys rather than choosing one silently.',nextTools:['validate_yaml']},
  {id:'yaml-subset',pattern:/aliases|anchors|explicit tags/,guidance:'Rewrite YAML anchors, aliases and tags as ordinary repeated YAML values; URLCode accepts a JSON-compatible YAML subset.',nextTools:['validate_yaml']},
  {id:'yaml-syntax',pattern:/invalid yaml|non-json yaml|yaml mapping keys/,guidance:'The file is not valid URLCode YAML: check indentation, quoting and that every key is a plain string. validate_yaml checks supplied text without reading the project.',nextTools:['validate_yaml']},
  {id:'extension-config',pattern:/invalid extension configuration/,guidance:'The named location under extensions.<name>.config does not match that extension\'s own configuration schema, which the operator host registers, not the core URLCode schema. The keyword in parentheses is the failed check (additionalProperties: unknown key, type, minLength and so on). Read the extension\'s configuration schema with get_extensions (or `urlcode extensions --host-file ... --json`) before editing it, then validate.',nextTools:['get_extensions','validate']},
  {id:'route-handler',pattern:/invalid configuration at \/routes\/[^ ]+ \(required\): missing required key/,guidance:'A route needs exactly one handler (redirect, respond, function, proxy, static, page, download and so on). The schema names the first handler it tried, so "missing required key" on a route usually means the route declares two handlers or misspells the one it has. Keep one handler and check its fields with get_capability.',nextTools:['get_capability','get_schema','validate']},
  {id:'schema',pattern:/invalid configuration at/,guidance:'The named location does not match the versioned URLCode schema. Ask get_schema for that field or get_capability for the handler before editing it.',nextTools:['get_schema','get_capability','validate']},
  {id:'function-initialization',pattern:/function initialization failed/,guidance:'The named module failed to load before any request: fix the syntax error at the named line, install or correct the imported package or path, or make the route\'s `export` name one the module exports (default when omitted). Validate again after the edit.',nextTools:['validate']},
  {id:'function-deadline',pattern:/function deadline exceeded/,guidance:'The function did not return within its deadline. Look for an unresolved promise or a slow upstream call; the deadline is the operator\'s --function-timeout-ms. `urlcode dev` prints the route behind the 504 on stderr.',nextTools:['explain']},
  {id:'function-execution',pattern:/function execution failed/,guidance:'A 502 "Function execution failed" deliberately hides the function\'s error from the client. Run `urlcode dev` (or `urlcode serve --debug-errors`): stderr gets a function_error line with the route, source file, export, message and stack.',nextTools:['explain']},
  {id:'revision-pin',pattern:/pinned to project revision/,guidance:'The operator policy grants bindings for an older project revision, and any change to routes, policies or function sources changes the revision. Run `urlcode permissions` to print the grants this revision requests, review them, and update the policy file (outside the project) with the new projectSha256.',nextTools:['get_manifest']},
  {id:'operator-grant',pattern:/denied by (revision-pinned )?operator policy/,guidance:'Bindings and egress need an operator grant; project YAML cannot grant itself access. Run `urlcode permissions` to print what the project requests, put the reviewed grants in a policy file outside the project, and pass it with --policy.',nextTools:['get_manifest']},
  {id:'missing-binding',pattern:/missing required (environment|secret) binding/,guidance:'The granted variable is not set. Set it in the host environment; `urlcode dev` also reads .env.local. An env binding can declare a `default` instead.',nextTools:['explain']},
  {id:'undeclared-input',pattern:/path placeholder requires an input|undeclared input|placeholder must reference a declared path input|proxy placeholder requires/,guidance:'Every {name} in a route path or destination needs a matching declaration under the route\'s inputs. Ask get_schema for route.inputs.',nextTools:['get_schema']},
  {id:'route-path',pattern:/route must be a literal absolute path|terminal \/\* wildcard|terminal \/\*\*/,guidance:'Route keys are literal absolute paths with whole-segment {parameters}; only static and extension routes end in /*, and a wildcard redirect ends in /**. Ask get_capability for the handler you are routing to.',nextTools:['get_capability','get_schema']},
  {id:'route-conflict',pattern:/overlap|duplicate route/,guidance:'Two routes claim the same requests. Remove or rename one, then use explain on the path to confirm which route now selects it.',nextTools:['explain','inspect']},
  {id:'project-file',pattern:/project file|referenced|file reference|reference must point to a file/,guidance:'This needs local project validation: confirm the referenced path is project-relative, exists, and is allowed by the selected route type.',nextTools:['validate']},
  {id:'unknown-name',pattern:/unknown (capability|schema path)/,guidance:'The name is not in the bundled catalog; the message lists the valid names. Pick one of those exactly.',nextTools:['list_capabilities','get_schema']},
  {id:'sandbox',pattern:/sandbox/,guidance:'Sandboxed routes cannot use Node or network APIs. Prefer a declarative handler or proxy; otherwise remove sandboxing only after a deliberate trust review.',nextTools:['get_capability']},
  {id:'port-in-use',pattern:/already in use/,guidance:'Another process holds the port. Pass --port with a free port, or stop the other process.',nextTools:[]},
];
