import { lstat, mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { ConfigError, assert } from './errors.ts';
import { readBoundedTgz } from './artifacts.ts';
import { digestHex as digest, isRecord as record, listCachedFiles, writeLockAtomic } from './extension-transport.ts';
import { bundleArchiveLimits, bundleDigestPattern, bundleExact, bundleNamePattern, bundleTagPattern, bundleText, bundleVersionPattern, parseBundleEntry, validateBundleFiles, type BundleLock, type LockedBundle } from './extension-bundle-catalog.ts';

export async function validateCachedBundle(root:string,item:LockedBundle):Promise<void>{const archive=await readFile(join(root,'.bundle.tgz'));assert(digest(archive)===item.sha256,`Cached extension bundle ${item.name} does not match its lockfile`);const files=readBoundedTgz(archive,bundleArchiveLimits);validateBundleFiles(files,item,item.coreVersion);const expected=['.bundle.tgz',...files.map(file=>file.path)].sort();assert(JSON.stringify(await listCachedFiles(root,'extension bundle'))===JSON.stringify(expected),`Cached extension bundle ${item.name} has unexpected files`);for(const file of files)assert(digest(await readFile(join(root,file.path)))===digest(file.bytes),`Cached extension bundle ${item.name} was modified`);}
export async function extractBundle(bytes:Uint8Array,item:Pick<LockedBundle,'name'|'version'|'entry'|'sha256'|'coreVersion'>,destination:string):Promise<void>{assert(digest(bytes)===item.sha256,`Extension bundle ${item.name} does not match its signed SHA-256`);const files=readBoundedTgz(bytes,bundleArchiveLimits);validateBundleFiles(files,item,item.coreVersion);const root=resolve(destination),temporary=join(tmpdir(),`urlcode-extension-bundle-${process.pid}-${Math.random().toString(16).slice(2)}`);await mkdir(temporary,{recursive:true});try{for(const file of files){const target=resolve(temporary,file.path),rel=relative(temporary,target);assert(rel&&!rel.startsWith('..'),'Unsafe extension bundle path');await mkdir(dirname(target),{recursive:true});await writeFile(target,file.bytes,{flag:'wx'});}await writeFile(join(temporary,'.bundle.tgz'),bytes,{flag:'wx'});await mkdir(dirname(root),{recursive:true});try{await rename(temporary,root);}catch{try{await validateCachedBundle(root,item as LockedBundle);return;}catch{throw new ConfigError(`Extension bundle cache entry ${item.sha256} already exists but is not identical`);}}}finally{await rm(temporary,{recursive:true,force:true});}}
export function bundleCachePath(project:string,sha256:string):string{assert(bundleDigestPattern.test(sha256),'Invalid extension bundle digest');return join(project,'.urlcode','extension-bundles',sha256);}
export async function readBundleLock(project:string):Promise<BundleLock>{let raw:unknown;try{const path=join(project,'urlcode.extension-bundles.lock.json'),info=await lstat(path);assert(info.isFile()&&!info.isSymbolicLink()&&info.nlink===1,'Extension bundle lockfile must be an ordinary file');raw=JSON.parse(await readFile(path,'utf8'));}catch(error){if(error instanceof ConfigError)throw error;throw new ConfigError('No extension bundle lockfile; install a bundle first');}assert(record(raw)&&raw.format===1&&Array.isArray(raw.bundles),'Invalid extension bundle lockfile');bundleExact(raw,['format','bundles'],'Extension bundle lockfile');const seen=new Set<string>(),bundles=raw.bundles.map(value=>{assert(record(value)&&record(value.catalog),'Invalid extension bundle lock entry');bundleExact(value,['name','version','asset','sha256','entry','catalog','coreVersion'],'Extension bundle lock entry');bundleExact(value.catalog,['tag','commit'],'Extension bundle lock catalog');const item={...parseBundleEntry(value,'extension bundle lock entry',false),catalog:{tag:bundleText(value.catalog.tag,'lock tag'),commit:bundleText(value.catalog.commit,'lock commit')},coreVersion:bundleText(value.coreVersion,'lock core version')};assert(bundleTagPattern.test(item.catalog.tag)&&/^[a-f0-9]{40}$/.test(item.catalog.commit)&&bundleVersionPattern.test(item.coreVersion)&&!seen.has(item.name),'Invalid or duplicate extension bundle lock entry');seen.add(item.name);return item;});return {format:1,bundles};}
export async function writeBundleLock(project:string,lock:BundleLock):Promise<void>{const path=join(project,'urlcode.extension-bundles.lock.json'),temporary=join(project,`.urlcode.extension-bundles.lock.${process.pid}.${Math.random().toString(16).slice(2)}`);await writeLockAtomic(path,temporary,lock);}
export function assertBundleName(name:string):void{assert(bundleNamePattern.test(name),'Invalid extension bundle name');}
