import { isAbsolute, join, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { readFile } from 'node:fs/promises';
import { ConfigError, assert } from './errors.ts';
import { createGithubTransport, createLocalGithubTransport, isRecord as record, peekCatalogCommit, verifiedReleaseAsset, type ReleaseAsset } from './extension-transport.ts';
import { assertBundleName, bundleCachePath, extractBundle, readBundleLock, validateCachedBundle, writeBundleLock } from './extension-bundle-cache.ts';
import { bundleArchiveLimits, bundleNamePattern, bundleTagPattern, bundleVersionPattern, parseBundleCatalog, type BundleCatalog, type BundleEntry, type BundleLock, type BundleTransport, type LockedBundle } from './extension-bundle-catalog.ts';

/** Verified, executable first-party bundles. Unlike extension artifacts, these are trusted operator code. */
export const BUNDLE_REPOSITORY='jimhoyd-com/urlcode';
export const BUNDLE_WORKFLOW='jimhoyd-com/urlcode/.github/workflows/extension-bundles.yml';
export { bundleCachePath, extractBundle, parseBundleCatalog, readBundleLock };
export type { BundleCatalog, BundleEntry, BundleLock, BundleTransport, LockedBundle };

export const githubBundleTransport:BundleTransport=createGithubTransport({repository:BUNDLE_REPOSITORY,workflow:BUNDLE_WORKFLOW,tagPattern:bundleTagPattern,exampleTag:'extension-bundles@v1.0.0',maxAssetSize:bundleArchiveLimits.archive,itemLabel:'extension bundle'});
/** The offline transport changes only where verified bytes come from, never the attestation policy. */
export function createLocalBundleTransport(directory:string):BundleTransport { assert(typeof directory==='string'&&directory.length>0&&directory.length<1024,'Invalid local extension bundle release path'); return createLocalGithubTransport({repository:BUNDLE_REPOSITORY,workflow:BUNDLE_WORKFLOW,tagPattern:bundleTagPattern,exampleTag:'extension-bundles@v1.0.0',maxAssetSize:bundleArchiveLimits.archive,itemLabel:'extension bundle',directory}); }
async function verified(assets:ReleaseAsset[],asset:string,release:string,transport:BundleTransport,expectedCommit?:string|((bytes:Uint8Array)=>string)):Promise<Uint8Array>{return verifiedReleaseAsset(assets,asset,release,transport,'extension bundle','urlcode-bundle-attest',expectedCommit);}

/** The first-party bundle names built for this core version; the signed catalog remains authoritative for install. */
export const BUNDLE_CATALOG_NAMES:readonly {name:string;description:string}[] = [
  {name:'ui',description:'Shared presentation: escaped templates, shadcn/ui partials, themes, translations'},
  {name:'ui-presentation',description:'ui\'s public primitives only (renderDocument, createPresentation, escapeHtml, table, and friends), signed and versioned separately from the ui bundle\'s host-activation entry: no host file, no extensions.ui config, no /assets/ui mount'},
  {name:'auth',description:'Accounts: password, passkeys, OIDC, email codes, TOTP, sessions, roles, account page'},
  {name:'admin',description:'Administration: users, sessions, roles, audit, approvals, cases, impersonation'},
  {name:'store',description:'Durable bounded JSON collections exposed as a typed CRUD API'},
  {name:'forms',description:'Bounded server-rendered form flows: escaped controls, admission, CSRF, validation'},
  {name:'mcp',description:'Declarative MCP (Model Context Protocol) tool server: JSON-RPC 2.0 framing, protocol negotiation, initialize/ping/tools-list/tools-call over a bounded, project-declared tool map'},
];
const editDistance=(a:string,b:string):number=>{let row=Array.from({length:b.length+1},(_,j)=>j);for(let i=1;i<=a.length;i++){const next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(row[j]!+1,next[j-1]!+1,row[j-1]!+(a[i-1]===b[j-1]?0:1));row=next;}return row[b.length]!;};
function closestBundleName(requested:string,known:readonly string[]):string|undefined{let best:string|undefined,bestScore=Infinity;for(const candidate of known){const prefix=Math.min(requested.length,candidate.length)>=2&&(candidate.startsWith(requested)||requested.startsWith(candidate));const distance=editDistance(requested,candidate),score=prefix?Math.min(distance,1):distance;if(score<=2&&score<Math.max(requested.length,candidate.length)&&score<bestScore){best=candidate;bestScore=score;}}return best;}
export function assertKnownBundleNames(names:readonly string[]):void { const known=BUNDLE_CATALOG_NAMES.map(item=>item.name);for(const requested of names) {if(known.includes(requested)) continue;const close=closestBundleName(requested.slice(0,64),known);throw new ConfigError(`Unknown extension bundle ${requested.slice(0,64)}${close?`; did you mean ${close}?`:'.'} Known bundles: ${known.join(', ')} (urlcode extension-bundles list)`);} }
function releaseFetchFailure(error:unknown,release:string):unknown { if(error instanceof Error && error.message===`Could not fetch extension bundle release ${release}`) return new ConfigError(`${error.message}. The extension-bundles release for a core version publishes on a separate workflow after the core release and can take a few minutes (commonly under ten) to appear; if this core version just released, wait and retry. To pin an explicit, already-published release instead, use --bundle-release <tag> (for example an earlier compatible extension-bundles@vX.Y.Z).`);return error; }
async function cachedInstall(project:string,release:string,bundleName:string):Promise<BundleLock|undefined>{let lock:BundleLock;try{lock=await readBundleLock(project);}catch{return undefined;}const cached=lock.bundles.find(item=>item.name===bundleName&&item.catalog.tag===release);if(!cached)return undefined;await validateCachedBundle(bundleCachePath(project,cached.sha256),cached);return lock;}
export async function installBundle(project:string,release:string,bundleName:string,transport:BundleTransport=githubBundleTransport):Promise<BundleLock>{assertBundleName(bundleName);assert(bundleTagPattern.test(release),'Invalid extension bundle release tag');const cached=await cachedInstall(project,release,bundleName);if(cached)return cached;if(transport===githubBundleTransport)assertKnownBundleNames([bundleName]);let assets:{name:string;url:string}[];try{assets=await transport.release(release);}catch(error){throw releaseFetchFailure(error,release);}const catalog=parseBundleCatalog(await verified(assets,'extension-bundles-catalog.json',release,transport,peekCatalogCommit),release),item=catalog.bundles.find(value=>value.name===bundleName);assert(item,`Extension bundle ${bundleName} is not in the signed catalog for ${release}; valid names: ${catalog.bundles.map(value=>value.name).sort().join(', ') || '(none)'}`);const revoked=catalog.revoked.find(value=>value.sha256===item.sha256);assert(!revoked,`Extension bundle ${bundleName} is revoked: ${revoked?.reason??'unknown reason'}`);const locked:{catalog:{tag:string;commit:string};coreVersion:string}&BundleEntry={...item,catalog:{tag:catalog.tag,commit:catalog.commit},coreVersion:catalog.coreVersion};await extractBundle(await verified(assets,item.asset,release,transport,catalog.commit),locked,bundleCachePath(project,item.sha256));let prior:BundleLock|undefined;try{prior=await readBundleLock(project);}catch{/* first install */}const bundles=(prior?.bundles??[]).filter(value=>value.name!==item.name);bundles.push(locked);bundles.sort((left,right)=>left.name.localeCompare(right.name));const lock={format:1 as const,bundles};await writeBundleLock(project,lock);return lock;}
export async function runningCoreVersion():Promise<string>{const raw:unknown=JSON.parse(await readFile(new URL('../../../package.json',import.meta.url),'utf8'));assert(record(raw)&&typeof raw.version==='string'&&bundleVersionPattern.test(raw.version),'Could not read the running core version');return raw.version;}
async function lockedBundle(project:string,bundleName:string):Promise<{root:string;item:LockedBundle}>{assert(bundleNamePattern.test(bundleName),'Invalid extension bundle name');const lock=await readBundleLock(project),item=lock.bundles.find(value=>value.name===bundleName);assert(item,`Extension bundle ${bundleName} is not locked`);assert(item.coreVersion===await runningCoreVersion(),`Extension bundle ${bundleName} requires core ${item.coreVersion}; this runtime is incompatible`);const root=bundleCachePath(project,item.sha256);await validateCachedBundle(root,item);return {root,item};}
/** Explicit host-only loader. It never reads project YAML, downloads, updates, or discovers code. */
export async function loadExtensionBundle(project:string,bundleName:string):Promise<Record<string,unknown>>{const {root,item}=await lockedBundle(project,bundleName);const module=await import(pathToFileURL(join(root,item.entry)).href);assert(module&&typeof module==='object',`Extension bundle ${bundleName} entry did not export a module`);return module as Record<string,unknown>;}
/** Resolves a locked bundle's own packaged CLI only after the same cache-integrity check as the loader. */
export async function resolveBundleExecutable(project:string,bundleName:string):Promise<string>{const {root}=await lockedBundle(project,bundleName),packageName=`@jimhoyd/urlcode-${bundleName}`,packageDir=join(root,'node_modules','@jimhoyd',`urlcode-${bundleName}`);let manifest:unknown;try{manifest=JSON.parse(await readFile(join(packageDir,'package.json'),'utf8'));}catch{throw new ConfigError(`Extension bundle ${bundleName} is missing its package manifest`);}assert(record(manifest)&&manifest.name===packageName,`Extension bundle ${bundleName} has an invalid package manifest`);const bin=manifest.bin;const binPath=typeof bin==='string'?bin:record(bin)?Object.values(bin).find((value):value is string=>typeof value==='string'):undefined;assert(typeof binPath==='string'&&binPath.length>0,`Extension bundle ${bundleName} does not package a command-line entry point`);const script=resolve(packageDir,binPath),rel=relative(packageDir,script);assert(rel.length>0&&!rel.startsWith('..')&&!isAbsolute(rel),`Extension bundle ${bundleName} has an unsafe executable path`);return script;}
