export {createPresentation,baseCatalogue,catalogueLimits} from './presentation.ts';
export type {Presentation,PresentationOptions,PresentationContext,LocalePreferences,ThemeVariables,Catalogue,PluralMessage} from './presentation.ts';
export {escapeHtml,field,button,alert,navigation,table,pagination,emptyState} from './components.ts';
export type {FieldOptions,FieldOption} from './components.ts';
export {renderDocument,documentContentSecurityPolicy} from './document.ts';
export type {DocumentOptions} from './document.ts';
export {stylesheet} from './styles.ts';
export { Markup, markup, isMarkup } from './escape.ts';
export { kitCatalogue, kitCatalogueFr, mergeCatalogues, compareCatalogues, placeholders } from './catalogue.ts';
export { resolveTheme, assetPath, localHref, colorNames } from './theme.ts';
export type { Theme, ResolvedTheme, Colors, ColorName } from './theme.ts';
export { compileTemplate, safeHref, TemplateError } from './template.ts';
export type { CompiledTemplate, ViewModel, ViewValue, PartialResolver } from './template.ts';
export { kitTemplates, kitTemplateNames } from './partials.ts';
export type { ShippedTemplate } from './partials.ts';
export { kitCss, kitCssLimit, kitAssets, contentHash } from './kit-styles.ts';
export type { Asset } from './kit-styles.ts';
export { createKit, attributes, pageLimits } from './kit.ts';
export type { Kit, KitOptions, KitReport, PageOptions, PageResult, PageLayout, ExtensionScript, NavigationItem, TemplateInfo, TemplateOrigin, ExtensionTemplates } from './kit.ts';

export {icon} from './icons.ts';
export type {IconName} from './icons.ts';
export {hiddenField,postForm,withDeadline} from './forms.ts';
export type {PostFormOptions} from './forms.ts';
// `urlcode init --with ui` resolves `scaffold` from this entry; the module is Node-free and writes nothing.
export {scaffold} from './host/scaffold.ts';
export type {ScaffoldRequest,ScaffoldResult,ScaffoldFile} from './host/scaffold.ts';
export {crudScreen,crudMarkup,crudFields,crudCopyKeys,fieldLabel} from './crud.ts';
export type {CrudCollection,CrudColumn,CrudFieldSpec,CrudScreenOptions} from './crud.ts';
export {crudScript} from './crud-script.ts';
