import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,posix,resolve} from 'node:path';
// The authoring documents in reading order. Missing files are skipped with a
// note in the output so the build works on branches that lack one.
export const DOCUMENTS: readonly string[]=['docs/FRAMEWORK.md','docs/AI-AUTHORING.md','docs/YAML-GUIDE.md','docs/YAML-REFERENCE.md','docs/SPECIFICATION.md','docs/ROUTING.md','docs/HTTP.md','docs/MIDDLEWARE.md','docs/ASSETS.md','docs/POLICIES.md','docs/SITE.md','docs/CONDITIONS.md','docs/EGRESS.md','docs/EXTENSIONS.md','docs/COMPOSING-A-SITE.md','docs/FUNCTION-SECURITY.md'];
export const GITHUB_BLOB='https://github.com/jimhoyd-com/urlcode/blob/main/';
// Token estimate: one token per four characters, the common rule of thumb for
// English prose and code. It is an estimate, not a tokenizer.
export const CHARS_PER_TOKEN=4;
export function estimateTokens(text: string): number {return Math.ceil(text.length/CHARS_PER_TOKEN);}
// Rewrites relative Markdown link targets in a document at `relPath` (repo-relative,
// POSIX separators) to absolute GitHub URLs. Absolute URLs, mailto: and
// same-page anchors are left alone; anchors on relative links are preserved.
export function absolutizeLinks(markdown: string,relPath: string): string {
  const base=posix.dirname(relPath);
  return markdown.replace(/\]\(([^)\s]+)\)/g,(whole,target: string)=>{
    if(/^(?:[a-z][a-z0-9+.-]*:|#|\/\/)/i.test(target))return whole;
    const [path,anchor]=target.split('#',2) as [string,string|undefined];
    const joined=posix.normalize(posix.join(base,path));
    if(joined.startsWith('..'))return whole;
    return `](${GITHUB_BLOB}${joined}${anchor===undefined?'':`#${anchor}`})`;
  });
}
// Demotes every ATX heading outside fenced code blocks by one level so each
// document nests under its level-1 section heading.
export function demoteHeadings(markdown: string): string {
  let fence: string|null=null;
  return markdown.split('\n').map(line=>{
    const open=/^\s*(`{3,}|~{3,})/.exec(line);
    if(open){const marker=open[1]!;if(fence===null)fence=marker;else if(marker[0]===fence[0] && marker.length>=fence.length)fence=null;return line;}
    if(fence!==null)return line;
    return /^#{1,5} /.test(line)?`#${line}`:line;
  }).join('\n');
}
export function slug(title: string): string {return title.toLowerCase().replace(/[^a-z0-9 -]/g,'').trim().replace(/\s+/g,'-');}
async function readOptional(root: string,relPath: string): Promise<string|null> {
  try {return await readFile(resolve(root,relPath),'utf8');}
  catch(error) {if((error as NodeJS.ErrnoException).code==='ENOENT')return null;throw error;}
}
export async function buildLlmsFull(root: string): Promise<string> {
  const index=await readOptional(root,'llms.txt');
  if(index===null)throw new Error('llms.txt is missing');
  // The llms.txt header is everything before its first section heading.
  const preamble=absolutizeLinks(index.split(/^## /m)[0]!.trim(),'llms.txt');
  const sections: {title: string;body: string;path: string;present: boolean}[]=[];
  for(const path of DOCUMENTS){
    const source=await readOptional(root,path);
    const fallback=path.replace(/^docs\//,'').replace(/\.md$/,'');
    if(source===null){sections.push({title:fallback,body:`_Not present in this revision: \`${path}\`._`,path,present:false});continue;}
    const title=/^# (.+)$/m.exec(source)?.[1]?.trim() ?? fallback;
    const body=demoteHeadings(absolutizeLinks(source.replace(/^# .+\n+/,''),path)).trim();
    sections.push({title,body,path,present:true});
  }
  const toc=sections.map((s,i)=>`${i+1}. [${s.title}](#${slug(s.title)})${s.present?'':' (missing)'}`).join('\n');
  const content=sections.map(s=>`# ${s.title}\n\nSource: ${GITHUB_BLOB}${s.path}\n\n${s.body}\n`).join('\n---\n\n');
  const body=`${preamble}\n\n## Contents\n\n${toc}\n\n---\n\n${content}`;
  const header=`<!-- Generated by scripts/build-llms-full.ts (npm run docs:llms). Do not edit; edit the source documents. -->\n<!-- Consolidated URLCode authoring reference: ${sections.filter(s=>s.present).length} documents, about ${estimateTokens(body).toLocaleString('en-US')} tokens (estimate: characters / ${CHARS_PER_TOKEN}). -->\n\n`;
  return header+body;
}
if(process.argv[1] && resolve(process.argv[1])===fileURLToPath(import.meta.url)){
  const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
  const outIndex=process.argv.indexOf('--out');
  const target=outIndex===-1?resolve(root,'llms-full.txt'):resolve(process.argv[outIndex+1] ?? 'llms-full.txt');
  const output=await buildLlmsFull(root);
  if(process.argv.includes('--check')){
    const current=await readFile(target,'utf8').catch(()=>null);
    if(current!==output){console.error('llms-full.txt is stale; run npm run docs:llms');process.exit(1);}
  }else await writeFile(target,output);
}
